/**
 * startup.briefing tool
 *
 * Reads the current startup briefing artifacts generated by the read-only
 * Graphify / readiness passes. This tool is intentionally read-only and
 * bounded: it returns the compact summary instead of the full report payload.
 */

import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { registerTool, type ToolResult } from '../tool-registry';

const ROOT = process.cwd();
const BRIEFING_JSON = join(ROOT, '.opencode', 'startup-briefing.json');
const BRIEFING_MD = join(ROOT, '.opencode', 'startup-briefing.md');

async function readJson<T>(filePath: string): Promise<T | null> {
  try {
    if (!existsSync(filePath)) return null;
    return JSON.parse(await readFile(filePath, 'utf8')) as T;
  } catch {
    return null;
  }
}

registerTool('startup.briefing', async (): Promise<ToolResult> => {
  const briefing = await readJson<Record<string, unknown>>(BRIEFING_JSON);

  if (!briefing) {
    return {
      ok: false,
      error:
        'Startup briefing not found. Run `npm run agent:startup-briefing` to refresh the read-only briefing artifacts.',
    };
  }

  const summary = {
    greeting: briefing.greeting ?? 'Hello James.',
    timestamp: briefing.timestamp ?? null,
    sinceLastWorked: briefing.sinceLastWorked ?? null,
    systems: briefing.systems ?? null,
    coverage: briefing.coverage ?? null,
    warnings: Array.isArray(briefing.warnings) ? briefing.warnings : [],
    nextLane: briefing.nextLane ?? null,
    recommendations: Array.isArray(briefing.recommendations) ? briefing.recommendations.slice(0, 5) : [],
    artifactPaths: {
      json: BRIEFING_JSON,
      markdown: BRIEFING_MD,
    },
  };

  return {
    ok: true,
    data: summary,
  };
});

