/**
 * startup.briefing tool
 *
 * Reads the current startup briefing artifacts generated by the read-only
 * Graphify / readiness passes. This tool is intentionally read-only and
 * bounded: it returns the compact summary instead of the full report payload.
 */

import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { registerTool, type ToolResult } from '../tool-registry';

const ROOT = process.cwd();
const BRIEFING_CANDIDATES = [
  {
    json: join(ROOT, '.opencode', 'startup-briefing.json'),
    md: join(ROOT, '.opencode', 'startup-briefing.md'),
  },
  {
    json: join(ROOT, '..', '.opencode', 'startup-briefing.json'),
    md: join(ROOT, '..', '.opencode', 'startup-briefing.md'),
  },
] as const;

async function readJson<T>(filePath: string): Promise<T | null> {
  try {
    if (!existsSync(filePath)) return null;
    return JSON.parse(await readFile(filePath, 'utf8')) as T;
  } catch {
    return null;
  }
}

registerTool('startup.briefing', async (): Promise<ToolResult> => {
  let briefingReport: Record<string, unknown> | null = null;
  let briefing: Record<string, unknown> | null = null;
  let resolvedJson = BRIEFING_CANDIDATES[0].json;
  let resolvedMd = BRIEFING_CANDIDATES[0].md;

  for (const candidate of BRIEFING_CANDIDATES) {
    const loaded = await readJson<Record<string, unknown>>(candidate.json);
    if (loaded) {
      briefingReport = loaded;
      briefing = (loaded.briefing as Record<string, unknown> | undefined)
        ?? (loaded.summary as Record<string, unknown> | undefined)
        ?? loaded;
      resolvedJson = candidate.json;
      resolvedMd = candidate.md;
      break;
    }
  }

  if (!briefingReport || !briefing) {
    return {
      ok: false,
      error:
        'Startup briefing not found. Run `npm run agent:startup-briefing` to refresh the read-only briefing artifacts.',
    };
  }

  const summary = {
    greeting: briefing.greeting ?? 'Hello James.',
    timestamp: briefing.timestamp ?? briefingReport?.generatedAt ?? null,
    sinceLastWorked: briefing.sinceLastWorked ?? null,
    systems: briefing.systems ?? null,
    coverage: briefing.coverage ?? null,
    warnings: Array.isArray(briefing.warnings) ? briefing.warnings : [],
    nextLane:
      briefing.nextLane
      ?? (briefing as { summary?: { runtimeCoverage?: { nextLane?: string; higherHopEnrichment?: { nextSafeAction?: string } } } }).summary?.runtimeCoverage?.nextLane
      ?? (briefing as { summary?: { higherHopEnrichment?: { nextSafeAction?: string } } }).summary?.higherHopEnrichment?.nextSafeAction
      ?? null,
    recommendations: Array.isArray(briefing.recommendations) ? briefing.recommendations.slice(0, 5) : [],
    artifactPaths: {
      json: resolvedJson,
      markdown: resolvedMd,
    },
  };

  return {
    ok: true,
    data: summary,
  };
});
