-- Atlas synthesis + history tables (2026-06-03)
-- Lineage audit findings:
--   atlas_feature_map: 5740 rows, 1478 distinct feature_ids, join key = feature_id (NOT source_ref)
--   task_semantic_packets: 210 rows, 12 distinct feature_ids, 10 overlap with atlas on feature_id
--   source_ref join = 0 overlap (packets have NULL source_ref; fix is in Phase B pipeline)
--   agent_pickup_queue: integer serial PK (Drizzle uuid fixed in tasks.ts)

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. atlas_feature_map_synthesized
--    Derived working memory. Joins atlas lineage → task packets → queue state.
--    Join key: feature_id (coarse bucket; source_ref join deferred until Phase B
--    backfills task_semantic_packets.source_ref from file_path).
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS atlas_feature_map_synthesized (
    source_ref              text        PRIMARY KEY,
    feature_id              text,
    related_feature_ids     jsonb       NOT NULL DEFAULT '[]'::jsonb,

    -- Semantic cluster state (from atlas_feature_map)
    som_cluster             text,
    centroid_id             text,
    qdrant_point_id         text,
    cluster_id              text,

    -- Task + queue aggregates (from task_semantic_packets / agent_pickup_queue)
    task_count              integer     NOT NULL DEFAULT 0,
    packet_count            integer     NOT NULL DEFAULT 0,
    ready_packet_count      integer     NOT NULL DEFAULT 0,
    last_packet_id          text,
    pickup_status           text,       -- status of most-recent queue entry for this feature

    -- Routing scores (populated by Phase B scoring pipeline)
    semantic_confidence     real,
    graph_distance          integer,
    behavior_score          real,
    test_score              real,

    -- Composite routing weight: 0.4·sem + 0.3·behavior + 0.2·test + 0.1·(1/(dist+1))
    routing_score           real
        GENERATED ALWAYS AS (
            COALESCE(semantic_confidence, 0) * 0.4 +
            COALESCE(behavior_score, 0)      * 0.3 +
            COALESCE(test_score, 0)          * 0.2 +
            CASE WHEN graph_distance IS NOT NULL
                 THEN 1.0 / (graph_distance + 1) * 0.1
                 ELSE 0 END
        ) STORED,

    -- Runtime state blob (route latency, cache hits, SSE packet fields, etc.)
    runtime_state           jsonb       NOT NULL DEFAULT '{}'::jsonb,

    last_verified_at        timestamptz NOT NULL DEFAULT now(),
    synthesized_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_afms_feature_id
    ON atlas_feature_map_synthesized (feature_id);

CREATE INDEX IF NOT EXISTS idx_afms_som_cluster
    ON atlas_feature_map_synthesized (som_cluster);

CREATE INDEX IF NOT EXISTS idx_afms_routing_score
    ON atlas_feature_map_synthesized (routing_score DESC NULLS LAST);

CREATE INDEX IF NOT EXISTS idx_afms_pickup_status
    ON atlas_feature_map_synthesized (pickup_status)
    WHERE pickup_status IS NOT NULL;

COMMENT ON TABLE atlas_feature_map_synthesized IS
    'Derived working memory. Joins atlas_feature_map + task_semantic_packets + agent_pickup_queue. '
    'Regenerated by scripts/atlas/build-synthesized-map.mjs. Do not edit manually.';

COMMENT ON COLUMN atlas_feature_map_synthesized.routing_score IS
    '0.4·semantic_confidence + 0.3·behavior_score + 0.2·test_score + 0.1·(1/(graph_distance+1)). '
    'Generated column — auto-recomputed on UPDATE.';

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. atlas_feature_map_history
--    Temporal snapshot log. Written by any pipeline that mutates atlas_feature_map.
--    Answers: what changed, when, and in which indexing pass.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS atlas_feature_map_history (
    id              bigserial   PRIMARY KEY,
    source_ref      text        NOT NULL,
    snapshot_at     timestamptz NOT NULL DEFAULT now(),
    indexing_pass   text,       -- e.g. 'graphify:semantic', 'phase-b-som', 'runtime-trace'

    -- Values at snapshot time
    feature_id      text,
    som_cluster     text,
    centroid_id     text,
    qdrant_point_id text,
    cluster_id      text,
    atlas_version   integer,

    -- Full row snapshot for diff queries
    snapshot        jsonb       NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_afmh_source_ref
    ON atlas_feature_map_history (source_ref, snapshot_at DESC);

CREATE INDEX IF NOT EXISTS idx_afmh_indexing_pass
    ON atlas_feature_map_history (indexing_pass, snapshot_at DESC);

COMMENT ON TABLE atlas_feature_map_history IS
    'Append-only temporal log of atlas_feature_map mutations. '
    'Use to answer: which files moved SOM clusters? which feature_ids disappeared? '
    'Written by indexing pipelines, never by application code.';

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. route_runtime_packets
--    Telemetry written by context-assembler when ACE packet fields are injected.
--    Captures the live query→packet→feature→cluster chain for observability.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS route_runtime_packets (
    id              bigserial   PRIMARY KEY,
    captured_at     timestamptz NOT NULL DEFAULT now(),

    -- Request identity
    route           text        NOT NULL,   -- e.g. '/api/sse/chat'
    query_hash      text,                   -- sha256 of query text
    query_preview   text,                   -- first 120 chars

    -- ACE packet fields (mirrors context-assembler injection at :1389-1396)
    source_refs     jsonb       NOT NULL DEFAULT '[]'::jsonb,
    feature_ids     jsonb       NOT NULL DEFAULT '[]'::jsonb,
    lane_ids        jsonb       NOT NULL DEFAULT '[]'::jsonb,
    cluster_id      text,
    som_cluster     text,
    qdrant_hits     integer,
    redis_hot_keys  jsonb       NOT NULL DEFAULT '[]'::jsonb,

    -- Performance
    latency_ms      integer,
    cache_hit       boolean     NOT NULL DEFAULT false,
    cache_tier      text,       -- 'l1_redis' | 'l2_bifrost' | 'l3_gpu' | null

    -- Outcome (populated post-response)
    user_id         integer,
    session_id      text,
    response_tokens integer
);

CREATE INDEX IF NOT EXISTS idx_rrp_captured_at
    ON route_runtime_packets (captured_at DESC);

CREATE INDEX IF NOT EXISTS idx_rrp_route
    ON route_runtime_packets (route, captured_at DESC);

CREATE INDEX IF NOT EXISTS idx_rrp_cluster_id
    ON route_runtime_packets (cluster_id)
    WHERE cluster_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_rrp_source_refs_gin
    ON route_runtime_packets USING gin (source_refs);

CREATE INDEX IF NOT EXISTS idx_rrp_feature_ids_gin
    ON route_runtime_packets USING gin (feature_ids);

COMMENT ON TABLE route_runtime_packets IS
    'ACE telemetry per chat request. Written by context-assembler after packet injection. '
    'Powers Atlas health score, orphan detection, and routing confidence recalibration.';
