-- Parent Atlas Graphify BM25 index control plane v1.
--
-- Manual / intentionally unapplied migration.
-- The document store remains codebase_chunk_index.search_vector with its GIN
-- index from 0019_bm25_search_vector.sql. PostgreSQL 18 may use bitmap scans
-- for that GIN index; no duplicate BM25 document table is introduced.
--
-- Identity contract:
--   workflow_id: stable logical workflow/configuration identity.
--   graphify_run_id: one completed Graphify source-manifest execution.
--   index_run_id: one indexing attempt, generated by the caller as a ULID.
--   source_manifest_digest: idempotency boundary for the source snapshot.
--
-- Safety contract:
--   * additive CREATE TABLE / CREATE INDEX / CREATE VIEW only;
--   * no backfill, delete, truncate, or live scheduling;
--   * graphify_runs is canonical input; index runs are an operational ledger;
--   * graphify_run deletion is restricted while an indexing receipt refers to it.

BEGIN;

CREATE TABLE IF NOT EXISTS public.graphify_bm25_index_runs (
  index_run_id text PRIMARY KEY,
  workflow_id text NOT NULL,
  graphify_run_id uuid NOT NULL
    REFERENCES public.graphify_runs(run_id) ON DELETE RESTRICT,
  index_kind text NOT NULL DEFAULT 'postgres_tsvector_english',
  source_manifest_digest text NOT NULL,
  parameters jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'QUEUED'
    CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED')),
  requested_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  completed_at timestamptz,
  indexed_count bigint NOT NULL DEFAULT 0
    CHECK (indexed_count >= 0),
  skipped_count bigint NOT NULL DEFAULT 0
    CHECK (skipped_count >= 0),
  error jsonb,
  lease_owner text,
  lease_expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT graphify_bm25_index_runs_id_ulid
    CHECK (index_run_id ~ '^[0-9A-HJKMNP-TV-Z]{26}$'),
  CONSTRAINT graphify_bm25_index_runs_manifest_sha256
    CHECK (source_manifest_digest ~ '^[a-f0-9]{64}$'),
  CONSTRAINT graphify_bm25_index_runs_terminal_timestamps
    CHECK (
      status NOT IN ('SUCCEEDED', 'FAILED', 'SKIPPED')
      OR completed_at IS NOT NULL
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS graphify_bm25_index_runs_idempotency_uq
  ON public.graphify_bm25_index_runs
    (workflow_id, index_kind, source_manifest_digest);

CREATE INDEX IF NOT EXISTS graphify_bm25_index_runs_status_idx
  ON public.graphify_bm25_index_runs (status, requested_at ASC);

CREATE INDEX IF NOT EXISTS graphify_bm25_index_runs_workflow_idx
  ON public.graphify_bm25_index_runs (workflow_id, requested_at DESC);

CREATE INDEX IF NOT EXISTS graphify_bm25_index_runs_graphify_run_idx
  ON public.graphify_bm25_index_runs (graphify_run_id, requested_at DESC);

COMMENT ON TABLE public.graphify_bm25_index_runs IS
  'Operational BM25 indexing receipts. Canonical documents remain in codebase_chunk_index.';
COMMENT ON COLUMN public.graphify_bm25_index_runs.index_run_id IS
  'Caller-generated ULID for sortable indexing-attempt correlation.';
COMMENT ON COLUMN public.graphify_bm25_index_runs.workflow_id IS
  'Stable logical workflow/configuration identity; not a per-attempt identifier.';
COMMENT ON COLUMN public.graphify_bm25_index_runs.parameters IS
  'Validated snapshot of graphify_runs.configuration used by this indexing attempt.';

CREATE OR REPLACE VIEW public.graphify_bm25_index_candidates AS
SELECT
  gr.run_id AS graphify_run_id,
  COALESCE(gr.configuration->>'workflow_id', 'graphify-default') AS workflow_id,
  gr.workspace_revision,
  gr.source_manifest_digest,
  gr.source_manifest_source_count,
  gr.repository_revision,
  gr.configuration AS parameters,
  gr.completed_at AS graphify_completed_at
FROM public.graphify_runs gr
WHERE gr.status = 'COMPLETED'
  AND gr.source_manifest_digest IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.graphify_bm25_index_runs ir
    WHERE ir.graphify_run_id = gr.run_id
      AND ir.index_kind = 'postgres_tsvector_english'
      AND ir.status = 'SUCCEEDED'
  );

COMMIT;

-- Scheduling is intentionally external to this migration.
-- The hourly worker should:
--   1. read graphify_bm25_index_candidates;
--   2. validate/copy parameters;
--   3. create a ULID index_run_id;
--   4. claim one row with a lease;
--   5. refresh/search_vector-backed codebase_chunk_index rows;
--   6. write SUCCEEDED/FAILED with counts.
-- Install pg_cron only after the worker command and non-production proof exist.