# Auto-generated by scene-compiler — do not edit by hand.
# Generator:    scene-compiler-0.1.0-phase-0b
# Plan hash:    4a5d9c80a8bccd82c50ac87e0a881f68
# Disclaimer:   Demonstrative reconstruction — not original footage

import bpy

# ── Scene parameters ─────────────────────────────────────
SCENE_ID    = "demo-2026-05-08-alleyway"
SCENE_TITLE = "Alleyway altercation — demo reconstruction"
CITY        = "downtown"
AESTHETIC   = "ps1"
DURATION_S  = 12
DISCLAIMER  = "Demonstrative reconstruction — not original footage"

# ── Reset scene to known state ───────────────────────────
bpy.ops.wm.read_factory_settings(use_empty=True)
scene = bpy.context.scene
scene.render.fps = 24
scene.frame_start = 1
scene.frame_end   = int(DURATION_S * 24)

# ── Actors ───────────────────────────────────────────────
# Actor suspect-1 — Suspect (male, dark jacket) (suspect)
bpy.ops.mesh.primitive_cube_add(location=(2, 0, 1))
bpy.context.object.name = "suspect-1"

# Actor victim-1 — Victim (female, light coat) (victim)
bpy.ops.mesh.primitive_cube_add(location=(4, 0, 1))
bpy.context.object.name = "victim-1"

# ── Events (timeline keyframes) ──────────────────────────
# Event evt-001 @ t=0s — walk (mixamo_walk_forward_01)
#   what: Suspect walks east into the alleyway from the street.
#   how:  Pedestrian gait, hands in jacket pockets per witness statement.
#   confidence: high
#   evidence:   ev-cctv-12, ev-witness-statement-A
obj_suspect_1 = bpy.data.objects.get("suspect-1")
if obj_suspect_1 is not None:
    obj_suspect_1.location = (0, 0, 0)
    obj_suspect_1.keyframe_insert(data_path="location", frame=1)
    obj_suspect_1.location = (4, 0, 0)
    obj_suspect_1.keyframe_insert(data_path="location", frame=72)

# Event evt-002 @ t=3s — idle (mixamo_idle_01)
#   what: Suspect and victim stop, brief verbal exchange.
#   how:  Both stationary, facing each other.
#   confidence: medium [DISPUTED]
#   evidence:   ev-witness-statement-B
obj_suspect_1 = bpy.data.objects.get("suspect-1")
if obj_suspect_1 is not None:
    obj_suspect_1.keyframe_insert(data_path="location", frame=72)
    obj_suspect_1.keyframe_insert(data_path="location", frame=168)
obj_victim_1 = bpy.data.objects.get("victim-1")
if obj_victim_1 is not None:
    obj_victim_1.keyframe_insert(data_path="location", frame=72)
    obj_victim_1.keyframe_insert(data_path="location", frame=168)

# Event evt-003 @ t=7s — fall (mixamo_fall_backward_01)
#   what: Victim falls backward.
#   how:  Fall consistent with backward push; head impact location matches blood-spatter at evidence pin ev-photo-spatter-04.
#   confidence: medium
#   evidence:   ev-photo-spatter-04, ev-coroner-report
obj_victim_1 = bpy.data.objects.get("victim-1")
if obj_victim_1 is not None:
    obj_victim_1.location = (4, 0, 0)
    obj_victim_1.keyframe_insert(data_path="location", frame=168)
    obj_victim_1.location = (4.2, 0, 0)
    obj_victim_1.keyframe_insert(data_path="location", frame=204)

# Event evt-004 @ t=8.5s — run (mixamo_run_01)
#   what: Suspect runs west out of the alleyway.
#   how:  Running gait, no items dropped per evidence inventory.
#   confidence: high
#   evidence:   ev-cctv-12
obj_suspect_1 = bpy.data.objects.get("suspect-1")
if obj_suspect_1 is not None:
    obj_suspect_1.location = (4, 0, 0)
    obj_suspect_1.keyframe_insert(data_path="location", frame=204)
    obj_suspect_1.location = (-2, 0, 0)
    obj_suspect_1.keyframe_insert(data_path="location", frame=288)

# ── Output ───────────────────────────────────────────────
# (Render configuration is set by the calling worker, not the script.)
print("scene-compiler: demo-2026-05-08-alleyway compiled")
