/**
 * scene-compiler.ts
 *
 * Pure-function compiler: validated `CrimeScenePlan` → `{ blenderScript,
 * sceneMetadata }`. NO model calls, NO file I/O, NO database — every
 * input maps deterministically to one output. Same plan → same script,
 * load-bearing for legal/audit review.
 *
 * The Blender script is built from a hand-templated string. Actions
 * resolve to Mixamo asset IDs via `MIXAMO_ACTION_MAP`; arbitrary verbs
 * are rejected at the schema layer (Zod).
 *
 * Phase 0B scope: deterministic compiler only. Does NOT shell out to
 * Blender. Does NOT call ComfyUI / Gemma4 / Qwen / TRELLIS. Does NOT
 * write files. Caller (compile-demo-scene.mjs) is responsible for I/O.
 */
import { createHash } from 'node:crypto';
import {
  CrimeScenePlanSchema,
  MIXAMO_ACTION_MAP,
  type CrimeScenePlan,
  type SceneMetadata,
} from './crime-scene-schema.js';

export const COMPILER_VERSION = 'scene-compiler-0.1.0-phase-0b';

export interface CompileResult {
  blenderScript:  string;   // Python script string, ready for `blender --background --python`
  sceneMetadata:  SceneMetadata;
  planHash:       string;   // sha256 of the canonical-JSON-serialized plan
}

function canonicalJson(value: unknown): string {
  // Deterministic JSON: sorted keys at every level. Hash of this string is
  // the plan's identity — same plan produces the same hash, even if the
  // input keys arrived in a different order.
  if (Array.isArray(value)) {
    return '[' + value.map(canonicalJson).join(',') + ']';
  }
  if (value && typeof value === 'object') {
    const keys = Object.keys(value as Record<string, unknown>).sort();
    return '{' + keys.map(k =>
      JSON.stringify(k) + ':' + canonicalJson((value as Record<string, unknown>)[k])
    ).join(',') + '}';
  }
  return JSON.stringify(value);
}

function hashPlan(plan: CrimeScenePlan): string {
  return createHash('sha256').update(canonicalJson(plan)).digest('hex').slice(0, 32);
}

// Indent blocks deterministically so script-string equality is meaningful in tests.
const I = '    ';

function pyStr(s: string): string {
  // Python triple-quote-safe single-line literal — escape backslash + quote.
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

function pyList(values: string[]): string {
  return '[' + values.map(pyStr).join(', ') + ']';
}

/**
 * Build the Blender Python script string. Caller is expected to write it
 * to disk then invoke `blender --background --python <path>` from a
 * RabbitMQ worker. The script itself does not import network, file I/O,
 * or shell — it only manipulates the bpy scene graph.
 */
// Convert an arbitrary actor_id into a Python-legal identifier.
// Same plan → same identifier, so the generated script stays deterministic.
function pyIdent(s: string): string {
  let out = s.replace(/[^A-Za-z0-9_]/g, '_');
  if (!/^[A-Za-z_]/.test(out)) out = '_' + out;
  return out;
}

function buildBlenderScript(plan: CrimeScenePlan, planHash: string): string {
  const lines: string[] = [];

  // No wallclock timestamp in the script header — keeps the .py byte-
  // deterministic so `same plan → same sha256` holds. The metadata JSON
  // still carries `compiled_at` for the audit trail.
  lines.push('# Auto-generated by scene-compiler — do not edit by hand.');
  lines.push(`# Generator:    ${COMPILER_VERSION}`);
  lines.push(`# Plan hash:    ${planHash}`);
  lines.push(`# Disclaimer:   ${plan.disclaimer}`);
  lines.push('');
  lines.push('import bpy');
  lines.push('');
  lines.push('# ── Scene parameters ─────────────────────────────────────');
  lines.push(`SCENE_ID    = ${pyStr(plan.scene_id)}`);
  lines.push(`SCENE_TITLE = ${pyStr(plan.title)}`);
  lines.push(`CITY        = ${pyStr(plan.city)}`);
  lines.push(`AESTHETIC   = ${pyStr(plan.aesthetic)}`);
  lines.push(`DURATION_S  = ${plan.duration_s}`);
  lines.push(`DISCLAIMER  = ${pyStr(plan.disclaimer)}`);
  lines.push('');
  lines.push('# ── Reset scene to known state ───────────────────────────');
  lines.push('bpy.ops.wm.read_factory_settings(use_empty=True)');
  lines.push('scene = bpy.context.scene');
  lines.push('scene.render.fps = 24');
  lines.push('scene.frame_start = 1');
  lines.push(`scene.frame_end   = int(DURATION_S * 24)`);
  lines.push('');
  lines.push('# ── Actors ───────────────────────────────────────────────');

  const actorIds = new Map<string, number>();
  let actorIdx = 0;
  for (const ev of plan.events) {
    for (const actor of ev.who) {
      if (!actorIds.has(actor.actor_id)) {
        actorIds.set(actor.actor_id, actorIdx++);
        lines.push(`# Actor ${actor.actor_id} — ${actor.label} (${actor.role})`);
        lines.push(`bpy.ops.mesh.primitive_cube_add(location=(${actorIdx * 2}, 0, 1))`);
        lines.push(`bpy.context.object.name = ${pyStr(actor.actor_id)}`);
        lines.push('');
      }
    }
  }

  lines.push('# ── Events (timeline keyframes) ──────────────────────────');
  for (const ev of plan.events) {
    const mixamoId = MIXAMO_ACTION_MAP[ev.action];
    lines.push(`# Event ${ev.id} @ t=${ev.time_s}s — ${ev.action} (${mixamoId})`);
    lines.push(`#   what: ${ev.what.replace(/\n/g, ' ')}`);
    lines.push(`#   how:  ${ev.how.replace(/\n/g, ' ')}`);
    lines.push(`#   confidence: ${ev.confidence}${ev.disputed ? ' [DISPUTED]' : ''}`);
    if (ev.evidence_ids.length > 0) {
      lines.push(`#   evidence:   ${ev.evidence_ids.join(', ')}`);
    }
    for (const actor of ev.who) {
      const objVar = `obj_${pyIdent(actor.actor_id)}`;
      lines.push(`${objVar} = bpy.data.objects.get(${pyStr(actor.actor_id)})`);
      lines.push(`if ${objVar} is not None:`);
      const startFrame = Math.max(1, Math.round(ev.time_s * 24));
      const endFrame   = Math.max(startFrame + 1, Math.round((ev.time_s + ev.duration_s) * 24));
      if (ev.path.length > 0) {
        for (const pt of ev.path) {
          const f = Math.max(1, Math.round((ev.time_s + pt.t) * 24));
          lines.push(`${I}${objVar}.location = (${pt.x}, ${pt.y}, ${pt.z})`);
          lines.push(`${I}${objVar}.keyframe_insert(data_path=${pyStr('location')}, frame=${f})`);
        }
      } else {
        lines.push(`${I}${objVar}.keyframe_insert(data_path=${pyStr('location')}, frame=${startFrame})`);
        lines.push(`${I}${objVar}.keyframe_insert(data_path=${pyStr('location')}, frame=${endFrame})`);
      }
    }
    lines.push('');
  }

  lines.push('# ── Output ───────────────────────────────────────────────');
  lines.push('# (Render configuration is set by the calling worker, not the script.)');
  lines.push(`print(${pyStr(`scene-compiler: ${plan.scene_id} compiled`)})`);
  lines.push('');

  return lines.join('\n');
}

function buildSceneMetadata(plan: CrimeScenePlan, planHash: string, compiledAt: string): SceneMetadata {
  const seenActors = new Map<string, { actor_id: string; role: typeof plan.events[0]['who'][0]['role']; label: string }>();
  const allEvidence = new Set<string>();
  const allAnnotations: SceneMetadata['annotations'] = [];

  for (const ev of plan.events) {
    for (const a of ev.who) {
      if (!seenActors.has(a.actor_id)) seenActors.set(a.actor_id, a);
    }
    for (const eid of ev.evidence_ids) allEvidence.add(eid);
    for (const ann of ev.annotations) allAnnotations.push(ann);
  }

  return {
    scene_id:    plan.scene_id,
    case_id:     plan.case_id,
    title:       plan.title,
    city:        plan.city,
    aesthetic:   plan.aesthetic,
    duration_s:  plan.duration_s,
    disclaimer:  plan.disclaimer,
    actors:      [...seenActors.values()],
    events: plan.events.map(ev => ({
      id:           ev.id,
      time_s:       ev.time_s,
      duration_s:   ev.duration_s,
      action:       ev.action,
      mixamo_id:    MIXAMO_ACTION_MAP[ev.action],
      actor_ids:    ev.who.map(w => w.actor_id),
      path:         ev.path,
      confidence:   ev.confidence,
      disputed:     ev.disputed,
      evidence_ids: ev.evidence_ids,
    })),
    annotations:  allAnnotations,
    evidence_ids: [...allEvidence],
    generator: {
      version:     COMPILER_VERSION,
      compiled_at: compiledAt,
      plan_hash:   planHash,
    },
  };
}

/**
 * Validate + compile in one call. Throws ZodError on schema violations.
 * Caller is responsible for catching, logging, and surfacing errors to
 * the worker / API layer.
 */
export function compileCrimeScene(planInput: unknown): CompileResult {
  const plan       = CrimeScenePlanSchema.parse(planInput);
  const planHash   = hashPlan(plan);
  const compiledAt = new Date().toISOString();
  return {
    blenderScript: buildBlenderScript(plan, planHash),
    sceneMetadata: buildSceneMetadata(plan, planHash, compiledAt),
    planHash,
  };
}
