import { sql } from 'drizzle-orm';
import { pgTable, text, integer, doublePrecision, bigint, jsonb, timestamp, index, uuid } from 'drizzle-orm/pg-core';
import { vector } from 'drizzle-orm/pg-core';
import { atlasTreeNodes } from './atlas-tree-nodes.js';

export const atlasPackets = pgTable('atlas_packets', {
  packetId: text('packet_id').primaryKey(),
  packetKey: text('packet_key'),
  artifactId: text('artifact_id').notNull(),
  sourceRef: text('source_ref'),
  sourcePath: text('source_path'),
  sourceKind: text('source_kind'),
  featureId: text('feature_id'),
  treeNodeId: uuid('tree_node_id').references(() => atlasTreeNodes.nodeId, { onDelete: 'set null' }),
  communityId: integer('community_id'),
  conceptIds: text('concept_ids').array(),
  clusterId: integer('cluster_id'),
  embedding: vector('embedding', { dimensions: 768 }),
  payload: jsonb('payload'),
  metadata: jsonb('metadata'),
  summary: text('summary'),
  byteStart: bigint('byte_start', { mode: 'number' }),
  byteEnd: bigint('byte_end', { mode: 'number' }),
  sha256: text('sha256'),
  rewardPrior: doublePrecision('reward_prior').default(0),
  sourceRefKey: text('source_ref_key'),
  communitySource: text('community_source'),
  communityConfidence: doublePrecision('community_confidence'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => ({
  payloadGin: index('atlas_packets_payload_gin').using('gin', table.payload),
  featureIdx: index('atlas_packets_feature_idx').on(table.featureId, table.communityId, table.clusterId),
  sourceRefIdx: index('idx_atlas_packets_source_ref').on(table.sourceRef),
  packetKeyIdx: index('idx_atlas_packets_packet_key').on(table.packetKey),
  sourceKindIdx: index('idx_atlas_packets_source_kind').on(table.sourceKind),
  communityIdIdx: index('idx_atlas_packets_community_id').on(table.communityId),
  featureIdIdx: index('idx_atlas_packets_feature_id').on(table.featureId),
  sourceRefKeyIdx: index('idx_atlas_packets_source_ref_key').on(table.sourceRefKey),
  conceptIdsIdx: index('idx_atlas_packets_concept_ids').using('gin', table.conceptIds),
  summaryFtsIdx: index('idx_atlas_packets_summary_fts').using('gin', sql`to_tsvector('english', coalesce(${table.summary}, ''))`),
  identityIdx: index('atlas_packets_identity_idx').on(table.packetKey, table.sourceRef, table.featureId, table.communityId),
  metadataGinIdx: index('atlas_packets_metadata_gin_idx').using('gin', table.metadata),
  metadataPathIdx: index('atlas_packets_metadata_path_idx').on(sql`(${table.metadata}->>'path')`),
  metadataHashIdx: index('atlas_packets_metadata_hash_idx').on(sql`(${table.metadata}->>'hash')`),
  payloadHashIdx: index('atlas_packets_payload_hash_idx').on(sql`(${table.payload}->>'hash')`),
  payloadPathIdx: index('idx_atlas_packets_payload_path').on(sql`(${table.payload}->>'path')`),
  payloadFileUrlIdx: index('idx_atlas_packets_payload_file_url').on(sql`(${table.payload}->>'file_url')`),
  treeNodeIdIdx: index('idx_atlas_packets_tree_node_id').on(table.treeNodeId),
  packetPayloadPathIdx: index('idx_packet_payload_path').on(sql`(${table.payload}->>'path')`),
  packetPayloadFeatureIdx: index('idx_packet_payload_feature').on(sql`(${table.payload}->>'feature_id')`),
}));
