import { sql } from 'drizzle-orm';
import { pgTable, bigserial, text, timestamp, integer, boolean, jsonb, index, numeric, uuid, uniqueIndex } from 'drizzle-orm/pg-core';
import { atlasTreeNodes } from './atlas-tree-nodes.js';

export const routeRuntimePackets = pgTable('route_runtime_packets', {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    capturedAt: timestamp('captured_at', { withTimezone: true }).defaultNow().notNull(),

    // Request identity
    route: text('route').notNull(),
    queryHash: text('query_hash'),
    queryPreview: text('query_preview'),
    packetKey: text('packet_key'),
    sourceRef: text('source_ref'),
    featureLabel: text('feature_label'),
    communityId: integer('community_id'),
    communityConfidence: numeric('community_confidence'),
    communitySource: text('community_source'),
    domainClass: text('domain_class'),
    ledgerType: text('ledger_type'),
    lineageVersion: text('lineage_version'),
    metadata: jsonb('metadata').notNull().default(sql`'{}'::jsonb`),
    tags: jsonb('tags').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    canonical: boolean('canonical').notNull().default(false),
    payloadBackfilledAt: timestamp('payload_backfilled_at', { withTimezone: true }),
    somRow: integer('som_row'),
    somCol: integer('som_col'),
    somIndex: integer('som_index'),
    kmeansCluster: integer('kmeans_cluster'),
    summary: text('summary'),

    // ACE packet fields
    sourceRefs: jsonb('source_refs').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    featureIds: jsonb('feature_ids').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    laneIds: jsonb('lane_ids').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    clusterId: text('cluster_id'),
    somCluster: text('som_cluster'),
    qdrantHits: integer('qdrant_hits'),
    redisHotKeys: jsonb('redis_hot_keys').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
    raw: jsonb('raw').notNull().default(sql`'{}'::jsonb`),
    treeNodeId: uuid('tree_node_id').references(() => atlasTreeNodes.nodeId, { onDelete: 'set null' }),
    promptHash: text('prompt_hash'),
    reward: numeric('reward'),
    packetUuid: uuid('packet_uuid').defaultRandom(),
    routeState: text('route_state'),
    featureId: text('feature_id'),
    packetVersion: integer('packet_version'),
    supersedesPacketUuid: uuid('supersedes_packet_uuid'),
    supersededBy: uuid('superseded_by'),
    gitSha: text('git_sha'),
    gitDiffRank: numeric('git_diff_rank'),
    sourceRefQuality: numeric('source_ref_quality'),
    repairReason: text('repair_reason'),
    repairMethod: text('repair_method'),

    // Performance
    latencyMs: integer('latency_ms'),
    cacheHit: boolean('cache_hit').notNull().default(false),
    cacheTier: text('cache_tier'),

    // Outcome
    userId: integer('user_id'),
    sessionId: text('session_id'),
    responseTokens: integer('response_tokens'),
  },
  (t) => [
    index('idx_rrp_captured_at').on(t.capturedAt.desc()),
    index('idx_rrp_route').on(t.route, t.capturedAt.desc()),
    index('idx_rrp_cluster_id').on(t.clusterId).where(sql`${t.clusterId} IS NOT NULL`),
    index('idx_route_runtime_packets_packet_key_idx').on(t.packetKey),
    index('idx_route_runtime_packets_source_ref_idx').on(t.sourceRef),
    index('idx_route_runtime_packets_source_ref').on(t.sourceRef),
    index('idx_route_runtime_packets_feature_label_idx').on(t.featureLabel),
    index('idx_route_runtime_packets_community_id_idx').on(t.communityId),
    index('idx_route_runtime_packets_community_confidence_idx').on(t.communityConfidence),
    index('idx_route_runtime_packets_community_source_idx').on(t.communitySource),
    index('idx_route_runtime_packets_domain_class_idx').on(t.domainClass),
    index('idx_route_runtime_packets_ledger_type_idx').on(t.ledgerType),
    index('idx_route_runtime_packets_lineage_version_idx').on(t.lineageVersion),
    index('idx_route_runtime_packets_metadata_gin').using('gin', t.metadata),
    index('idx_route_runtime_packets_tags_gin').using('gin', t.tags),
    index('idx_route_runtime_packets_som_row_idx').on(t.somRow),
    index('idx_route_runtime_packets_som_col_idx').on(t.somCol),
    index('idx_route_runtime_packets_som_index_idx').on(t.somIndex),
    index('idx_route_runtime_packets_kmeans_cluster_idx').on(t.kmeansCluster),
    index('idx_rrp_source_refs_gin').using('gin', t.sourceRefs),
    index('idx_rrp_feature_ids_gin').using('gin', t.featureIds),
    index('idx_route_runtime_packets_feature_id').on(t.featureId),
    index('idx_route_runtime_packets_feature_id_idx').on(t.featureId),
    index('idx_route_runtime_packets_feature_ids_gin').using('gin', t.featureIds),
    index('idx_route_runtime_packets_source_refs_gin').using('gin', t.sourceRefs),
    index('idx_route_runtime_packets_tree_node_id').on(t.treeNodeId),
    index('idx_route_runtime_packets_raw_gin').using('gin', t.raw),
    index('idx_rrp_git_sha').on(t.gitSha),
    index('idx_rrp_packet_version').on(t.packetVersion),
    index('idx_rrp_source_ref_quality').on(t.sourceRefQuality),
    index('idx_rrp_superseded_by').on(t.supersededBy),
    index('rrp_raw_gin').using('gin', t.raw),
    index('rrp_state_idx').on(t.routeState, t.capturedAt.desc()),
    index('rrp_feature_idx').on(t.featureId, t.capturedAt.desc()),
    uniqueIndex('rrp_packet_uuid_uidx').on(t.packetUuid),
  ]
);

export type RouteRuntimePacket = typeof routeRuntimePackets.$inferSelect;
export type NewRouteRuntimePacket = typeof routeRuntimePackets.$inferInsert;
