/**
 * HyperGraphRAG types.
 *
 * A hyperedge connects N heterogeneous members (query, files, clusters,
 * LLMS.md context, prior answers, tests) in a single relation.
 * Unlike binary graph edges (IMPORTS, SIMILAR_TO) a hyperedge is n-ary.
 *
 * Search modes (GraphSearch-inspired):
 *   'hop1'     — GraphSearch-R step: immediate structural neighbors of anchor_key
 *   'multihop' — GraphSearch-R full: recursive hop-by-hop expansion up to max_hops
 *   'global'   — GraphSearch-F: flat retrieval from full corpus without hop constraint
 */

export const EDGE_TYPES = [
  'retrieval',       // ACE/RAG retrieval run — query → chunks + clusters + LLMS.md
  'fix_attempt',     // ops.record_fix_attempt — file + test + operator token hash + prior answer
  'test_coverage',   // test file covers source files
  'cluster_context', // cluster annotation — files belonging to a GPU/SOM cluster
  'agents_context',  // LLMS.md walk-up binding — file + relevant LLMS.md nodes
  'shared_resource', // shared resource edge — cross-cluster file dependency
  'vault_link',      // vault markdown link edge
  'topo_context',    // topology context edge — SOM neighborhood
] as const;

export type EdgeType = typeof EDGE_TYPES[number];

export const MEMBER_KINDS = [
  'query',         // hashed query string
  'file',          // source file stable_key
  'LLMS.md',     // LLMS.md Redis key (llms:dir:<path> or llms:root)
  'cluster',       // GPU/SOM cluster id
  'prior_answer',  // code_llm_index / ace_hits stable_key
  'test',          // test file stable_key
  'chunk',         // Qdrant chunk id
  'neo4j_node',    // Neo4j node id
] as const;

export type MemberKind = typeof MEMBER_KINDS[number];

export const MEMBER_ROLES = ['source', 'context', 'result', 'constraint', 'evidence'] as const;
export type MemberRole = typeof MEMBER_ROLES[number];

export const SEARCH_MODES = ['hop1', 'multihop', 'global'] as const;
export type SearchMode = typeof SEARCH_MODES[number];

// ── Topology metadata ─────────────────────────────────────────────────────────

export interface HyperedgeTopology {
  topo_class?: string;
  topo_hex?: string;
  topo_byte?: number;
  som_cluster?: number | string;
  glyph_cluster?: string;
  manifold4?: [number, number, number, number];
  graphAuthorityScore?: number;
}

// ── Score breakdown ────────────────────────────────────────────────────────────
// GraphSearch hybrid score: final = α·coverage + β·weight + γ·anchor_sim + δ·query_sim + bonuses
//
// Weights (when embeddings are available):
//   memberCoverage  × 0.40
//   query_similarity × 0.25   (candidate ↔ query semantic similarity)
//   anchor_similarity × 0.20  (candidate ↔ anchor structural similarity, GraphSearch-R)
//   roleWeight       × 0.10   (source/result > context bonus)
//   topology + lexical + graphAuthority × 0.05 combined
//
// Without embeddings (base case):
//   memberCoverage  × 0.50
//   weight          × 0.20
//   roleWeight + topology + lexical + graphAuthority split remaining 0.30

export interface HyperedgeScoreBreakdown {
  memberCoverage?: number;     // matched_members / total_members
  query_similarity?: number;   // cosine(query_embedding, candidate_embedding) — GraphSearch-F
  anchor_similarity?: number;  // cosine(anchor_embedding, candidate_embedding) — GraphSearch-R
  roleWeight?: number;         // bonus for source/result roles over context
  graphAuthority?: number;     // Neo4j PageRank / graphAuthorityScore contribution
  topology?: number;           // topo_class / glyph_cluster alignment bonus
  lexical?: number;            // FTS / member_key match contribution
  final: number;               // weighted sum used for ranking
}

// ── HCA card ──────────────────────────────────────────────────────────────────

export interface HyperedgeCard {
  edge_id: string;
  summary128: string;
  memberKeys: string[];
  tags: string[];
  topology?: HyperedgeTopology;
}

// ── Core types ────────────────────────────────────────────────────────────────

export interface HyperedgeMember {
  id?: number;
  edge_id?: string;
  member_kind: MemberKind;
  member_key: string;
  role?: MemberRole;
  score?: number;
  payload?: Record<string, unknown>;
}

export interface HyperedgeInput {
  /** Optional stable id — if omitted, UUID is generated by Postgres. */
  id?: string;
  edge_type: EdgeType;
  label?: string;
  query_hash?: string;
  run_id?: string;
  weight?: number;
  topology?: HyperedgeTopology;
  metadata?: Record<string, unknown>;
  members: HyperedgeMember[];
}

export interface Hyperedge {
  id: string;
  edge_type: EdgeType;
  label: string | null;
  query_hash: string | null;
  run_id: string | null;
  weight: number;
  topology?: HyperedgeTopology | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
  members: HyperedgeMember[];
}

export interface HyperedgeSearchParams {
  member_key?: string;
  member_kind?: MemberKind;
  edge_type?: EdgeType;
  run_id?: string;
  query_hash?: string;
  limit?: number;
  offset?: number;
  /** GraphSearch mode: 'hop1' | 'multihop' | 'global' (default 'global') */
  search_mode?: SearchMode;
  /** Anchor node for hop-based traversal (GraphSearch-R) */
  anchor_key?: string;
  /** Max hops for multihop mode (default 2) */
  max_hops?: number;
}

export interface HyperedgeSearchResult {
  edge: Hyperedge;
  activationScore: number;
  scoreBreakdown: HyperedgeScoreBreakdown;
  matchedMembers: string[];
  rankPosition: number;
  whySelected: string[];
  card?: HyperedgeCard;
}

export interface HyperedgeSearchResponse {
  results: HyperedgeSearchResult[];
  totalMatched: number;
  durationMs: number;
}

export interface HyperedgeActivation {
  edge: Hyperedge | null;
  activatedByTerms: string[];
  membersCovered: number;
  coverageRatio: number;
}

export interface HyperedgeExpansion {
  edge: Hyperedge | null;
  relatedEdges: Hyperedge[];
}

// ── Traversal (GraphSearch-R / GraphSearch-F) ─────────────────────────────────

export interface TraversalStep {
  hop: number;
  anchor_key: string;
  candidates: string[];     // member_keys found at this hop
  scores: Record<string, number>;
}

export interface TraversalResult {
  mode: SearchMode;
  anchor_key: string;
  steps: TraversalStep[];
  edges: Hyperedge[];
  totalHops: number;
  durationMs: number;
}
