import type { Pool, PoolClient } from 'pg';
import { z } from 'zod';
import { reviewedIdentityAliasSchema, type ReviewedIdentityAliasV1 } from './reviewed-identity-alias.js';
import { createSchemaObjectRegistryRepository, schemaObjectNominationSchema, type SchemaObjectNominationV1, type SchemaObjectResolutionV1 } from './schema-object-registry.js';
import { createTestCaseRegistryRepository, testCaseNominationSchema, type TestCaseNominationV1, type TestCaseResolutionV1 } from './test-case-registry.js';

const applicationReceiptSchema=z.object({schema:z.literal('atlas.reviewed-alias-application-receipt.v1').default('atlas.reviewed-alias-application-receipt.v1'),decision_id:z.string().min(1),entity_kind:z.enum(['test','schema_object']),stable_id:z.string().min(1),new_key:z.string().min(1),resolution_basis:z.enum(['explicit_rename','explicit_move','human_review']),registry_revision:z.string().min(1),producer_revision:z.string().min(1)}).strict();
export type ReviewedAliasApplicationReceiptV1=z.infer<typeof applicationReceiptSchema>;
function basis(d:ReviewedIdentityAliasV1):ReviewedAliasApplicationReceiptV1['resolution_basis']{if(d.transition==='move')return'explicit_move';if(d.transition==='rename'||d.transition==='rename_and_move')return'explicit_rename';return'human_review';}
async function persistDecision(client:PoolClient,d:ReviewedIdentityAliasV1){await client.query(`INSERT INTO atlas_identity_alias_decisions(decision_id,entity_kind,stable_id,old_key,new_key,transition_kind,old_source_ref,new_source_ref,old_revision,new_revision,evidence_refs,reviewer_id,workflow_action_id,reviewed_at,registry_revision,producer_revision) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,$13,$14,$15,$16) ON CONFLICT(decision_id) DO NOTHING`,[d.decision_id,d.entity_kind,d.stable_id,d.old_key,d.new_key,d.transition,d.old_source_ref??null,d.new_source_ref??null,d.old_revision,d.new_revision,JSON.stringify(d.evidence_refs),d.reviewer_id,d.workflow_action_id,d.reviewed_at,d.registry_revision,d.producer_revision]);}
async function insertAliasProjection(client:PoolClient,d:ReviewedIdentityAliasV1){const kind=d.transition==='move'?'move':d.transition==='rename'||d.transition==='rename_and_move'?'rename':'human';if(d.entity_kind==='schema_object'){await client.query(`INSERT INTO atlas_schema_object_aliases(alias_key,stable_schema_object_id,alias_kind,source_ref,source_revision,evidence_refs,registry_revision) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7) ON CONFLICT(alias_key,stable_schema_object_id) DO NOTHING`,[d.new_key,d.stable_id,kind,d.new_source_ref??null,d.new_revision,JSON.stringify(d.evidence_refs),d.registry_revision]);return;}await client.query(`INSERT INTO atlas_test_aliases(alias_key,stable_test_id,alias_kind,source_ref,source_revision,evidence_refs,registry_revision) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7) ON CONFLICT(alias_key,stable_test_id) DO NOTHING`,[d.new_key,d.stable_id,kind,d.new_source_ref??null,d.new_revision,JSON.stringify(d.evidence_refs),d.registry_revision]);}

async function applyDecisionProjection(pool:Pool,d:ReviewedIdentityAliasV1):Promise<void>{const client=await pool.connect();try{await client.query('BEGIN');const table=d.entity_kind==='schema_object'?'atlas_schema_object_registry':'atlas_test_registry';const aliases=d.entity_kind==='schema_object'?'atlas_schema_object_aliases':'atlas_test_aliases';const idColumn=d.entity_kind==='schema_object'?'stable_schema_object_id':'stable_test_id';const current=await client.query<{canonical_key:string}>(`SELECT canonical_key FROM ${table} WHERE ${idColumn}=$1 AND status='active' FOR UPDATE`,[d.stable_id]);if(current.rowCount!==1)throw new Error(`REVIEWED_ALIAS_STABLE_ID_MISSING:${d.stable_id}`);const oldAlias=await client.query(`SELECT 1 FROM ${aliases} WHERE ${idColumn}=$1 AND alias_key=$2`,[d.stable_id,d.old_key]);const oldKeyBelongs=current.rows[0]!.canonical_key===d.old_key||oldAlias.rowCount===1;if(!oldKeyBelongs)throw new Error(`REVIEWED_ALIAS_OLD_KEY_MISMATCH:${d.decision_id}`);await persistDecision(client,d);await insertAliasProjection(client,d);await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}

export async function applyReviewedSchemaAlias(pool:Pool,input:{decision:ReviewedIdentityAliasV1;nomination:SchemaObjectNominationV1}):Promise<{resolution:SchemaObjectResolutionV1;receipt:ReviewedAliasApplicationReceiptV1}>{const d=reviewedIdentityAliasSchema.parse(input.decision);const n=schemaObjectNominationSchema.parse(input.nomination);if(d.entity_kind!=='schema_object')throw new Error('REVIEWED_ALIAS_ENTITY_KIND_MISMATCH:schema_object');if(d.new_key!==n.object_key)throw new Error('REVIEWED_ALIAS_NEW_KEY_MISMATCH:schema_object');await applyDecisionProjection(pool,d);const resolved=await createSchemaObjectRegistryRepository(pool).resolveNomination({nomination:n,registry_revision:d.registry_revision});if(resolved.status!=='canonical'||resolved.stable_schema_object_id!==d.stable_id)throw new Error(`REVIEWED_ALIAS_RESOLUTION_FAILED:${d.decision_id}`);const resolution={...resolved,resolution_basis:basis(d),evidence_refs:d.evidence_refs} as SchemaObjectResolutionV1;return{resolution,receipt:applicationReceiptSchema.parse({decision_id:d.decision_id,entity_kind:d.entity_kind,stable_id:d.stable_id,new_key:d.new_key,resolution_basis:basis(d),registry_revision:d.registry_revision,producer_revision:d.producer_revision})};}
export async function applyReviewedTestAlias(pool:Pool,input:{decision:ReviewedIdentityAliasV1;nomination:TestCaseNominationV1}):Promise<{resolution:TestCaseResolutionV1;receipt:ReviewedAliasApplicationReceiptV1}>{const d=reviewedIdentityAliasSchema.parse(input.decision);const n=testCaseNominationSchema.parse(input.nomination);if(d.entity_kind!=='test')throw new Error('REVIEWED_ALIAS_ENTITY_KIND_MISMATCH:test');if(d.new_key!==n.test_key)throw new Error('REVIEWED_ALIAS_NEW_KEY_MISMATCH:test');await applyDecisionProjection(pool,d);const resolved=await createTestCaseRegistryRepository(pool).resolveNomination({nomination:n,registry_revision:d.registry_revision});if(resolved.status!=='canonical'||resolved.stable_test_id!==d.stable_id)throw new Error(`REVIEWED_ALIAS_RESOLUTION_FAILED:${d.decision_id}`);const resolution={...resolved,resolution_basis:basis(d),evidence_refs:d.evidence_refs} as TestCaseResolutionV1;return{resolution,receipt:applicationReceiptSchema.parse({decision_id:d.decision_id,entity_kind:d.entity_kind,stable_id:d.stable_id,new_key:d.new_key,resolution_basis:basis(d),registry_revision:d.registry_revision,producer_revision:d.producer_revision})};}
