/**
 * Edit Anchor Extractor (Gap 3)
 * Produces patch-capable AST anchors with byte offsets, hashes, and resolution data
 */

import { createHash } from 'crypto';
import { readFileSync } from 'fs';
import { AstEditAnchor } from './patch-context-types.js';

/**
 * Compute SHA-256 hash of content
 */
function hashContent(content: string): string {
  return createHash('sha256').update(content).digest('hex');
}

/**
 * Normalize line endings for consistent hashing
 */
function normalizeLineEndings(content: string): string {
  return content.replace(/\r\n/g, '\n');
}

/**
 * Convert byte offset to row/column (line/character position)
 */
function byteOffsetToRowCol(
  content: string,
  byteOffset: number
): { row: number; column: number } {
  const normalized = normalizeLineEndings(content);
  let currentByte = 0;
  let row = 0;
  let column = 0;

  for (const char of normalized) {
    if (currentByte >= byteOffset) break;
    if (char === '\n') {
      row++;
      column = 0;
    } else {
      column++;
    }
    currentByte += Buffer.byteLength(char, 'utf8');
  }

  return { row, column };
}

/**
 * Convert row/column to byte offset
 */
function rowColToByteOffset(
  content: string,
  row: number,
  column: number
): number {
  const normalized = normalizeLineEndings(content);
  const lines = normalized.split('\n');
  let byteOffset = 0;

  for (let i = 0; i < row && i < lines.length; i++) {
    byteOffset += Buffer.byteLength(lines[i], 'utf8') + 1; // +1 for \n
  }

  if (row < lines.length) {
    byteOffset += Buffer.byteLength(lines[row].substring(0, column), 'utf8');
  }

  return byteOffset;
}

/**
 * Extract node text from content by byte range
 */
function extractNodeText(content: string, startByte: number, endByte: number): string {
  const normalized = normalizeLineEndings(content);
  const buffer = Buffer.from(normalized, 'utf8');
  return buffer.subarray(startByte, endByte).toString('utf8');
}

/**
 * Generate unique anchor ID from file + node hash + byte range
 */
function generateAnchorId(filePath: string, nodeHash: string, startByte: number, endByte: number): string {
  const key = `${filePath}::${nodeHash}::${startByte}-${endByte}`;
  return createHash('sha256').update(key).digest('hex');
}

/**
 * Detect node kind from source text (simplified heuristic)
 */
function detectNodeKind(text: string): string {
  text = text.trim();

  if (text.startsWith('import ') || text.startsWith('export import')) {
    return 'import_declaration';
  }
  if (text.startsWith('export ') || text.startsWith('export function') || text.startsWith('export class')) {
    return 'export_declaration';
  }
  if (text.match(/^\s*(async\s+)?function\s+\w+/)) {
    return 'function_definition';
  }
  if (text.match(/^\s*class\s+\w+/)) {
    return 'class_declaration';
  }
  if (text.match(/^\s*interface\s+\w+/)) {
    return 'interface_declaration';
  }
  if (text.match(/^\s*type\s+\w+\s*=/)) {
    return 'type_alias';
  }
  if (text.match(/^\s*const\s+\w+\s*=/)) {
    return 'variable_declaration';
  }
  if (text.match(/^\s*if\s*\(/)) {
    return 'if_statement';
  }
  if (text.match(/^\s*for\s*\(/)) {
    return 'for_statement';
  }
  if (text.match(/^\s*while\s*\(/)) {
    return 'while_statement';
  }
  if (text.match(/^\s*try\s*\{/)) {
    return 'try_statement';
  }
  if (text.match(/^\s*switch\s*\(/)) {
    return 'switch_statement';
  }
  if (text.match(/^\s*return\s+/)) {
    return 'return_statement';
  }
  if (text.match(/^\s*\w+\s*\(/)) {
    return 'function_call';
  }
  if (text.match(/^\s*\w+\s*=/)) {
    return 'assignment';
  }

  return 'expression_statement';
}

/**
 * Extract symbol name from node text
 */
function extractSymbolName(text: string, nodeKind: string): string | undefined {
  text = text.trim();

  if (nodeKind === 'function_definition') {
    const match = text.match(/function\s+(\w+)/);
    return match?.[1];
  }
  if (nodeKind === 'class_declaration') {
    const match = text.match(/class\s+(\w+)/);
    return match?.[1];
  }
  if (nodeKind === 'interface_declaration') {
    const match = text.match(/interface\s+(\w+)/);
    return match?.[1];
  }
  if (nodeKind === 'type_alias') {
    const match = text.match(/type\s+(\w+)/);
    return match?.[1];
  }
  if (nodeKind === 'variable_declaration') {
    const match = text.match(/const\s+(\w+)/);
    return match?.[1];
  }
  if (nodeKind === 'import_declaration') {
    const match = text.match(/from\s+['"](.*?)['"]/);
    return match?.[1];
  }

  return undefined;
}

/**
 * Detect if code appears to be generated (scaffolding, auto-generated markers, etc.)
 */
function isGeneratedCode(text: string): boolean {
  const markers = [
    /autogenerated/i,
    /auto-generated/i,
    /scaffold/i,
    /generated by/i,
    /do not edit/i,
    /donoteditmakeyourchangeselsewhere/i,
  ];

  return markers.some(marker => marker.test(text));
}

/**
 * Check if parsed syntax is valid (simplified: no unclosed braces/parens)
 */
function isParseValid(text: string): boolean {
  let braceCount = 0;
  let parenCount = 0;
  let bracketCount = 0;
  let inString = false;
  let stringChar = '';
  let inComment = false;

  for (let i = 0; i < text.length; i++) {
    const char = text[i];
    const prevChar = i > 0 ? text[i - 1] : '';

    // Handle strings
    if (!inComment && (char === '"' || char === "'" || char === '`') && prevChar !== '\\') {
      if (!inString) {
        inString = true;
        stringChar = char;
      } else if (char === stringChar) {
        inString = false;
      }
      continue;
    }

    if (inString) continue;

    // Handle comments
    if (!inComment && char === '/' && text[i + 1] === '/') {
      inComment = true;
      i = text.indexOf('\n', i) - 1;
      if (i === -2) break; // End of text
      continue;
    }

    // Count braces
    if (char === '{') braceCount++;
    if (char === '}') braceCount--;
    if (char === '(') parenCount++;
    if (char === ')') parenCount--;
    if (char === '[') bracketCount++;
    if (char === ']') bracketCount--;
  }

  return braceCount === 0 && parenCount === 0 && bracketCount === 0;
}

/**
 * Create an AST edit anchor from file content and byte range
 */
export function createEditAnchor(
  filePath: string,
  startByte: number,
  endByte: number,
  fileContent?: string,
  sourceRevision: number = 0
): AstEditAnchor | null {
  try {
    // Read file if not provided
    const content = fileContent || readFileSync(filePath, 'utf-8');
    const normalized = normalizeLineEndings(content);

    // Validate byte range
    if (startByte < 0 || endByte > normalized.length || startByte > endByte) {
      return null;
    }

    const nodeText = extractNodeText(normalized, startByte, endByte);
    const nodeKind = detectNodeKind(nodeText);
    const sourceHash = hashContent(normalized);
    const nodeHash = hashContent(nodeKind + '|' + normalizeLineEndings(nodeText));
    const startPoint = byteOffsetToRowCol(normalized, startByte);
    const endPoint = byteOffsetToRowCol(normalized, endByte);

    const anchor: AstEditAnchor = {
      anchorId: generateAnchorId(filePath, nodeHash, startByte, endByte),
      filePath,
      language: detectLanguageFromPath(filePath),
      nodeKind,
      nodeText,
      startByte,
      endByte,
      startPoint,
      endPoint,
      symbolName: extractSymbolName(nodeText, nodeKind),
      sourceHash,
      nodeHash,
      sourceRevision,
      parseNodeId: `${filePath}:${startByte}-${endByte}`,
      parseValid: isParseValid(nodeText),
      generatedCode: isGeneratedCode(nodeText),
    };

    return anchor;
  } catch (error) {
    console.error(`Failed to create edit anchor for ${filePath}:`, error);
    return null;
  }
}

/**
 * Detect language from file extension
 */
function detectLanguageFromPath(filePath: string): string {
  if (filePath.endsWith('.tsx')) return 'tsx';
  if (filePath.endsWith('.ts')) return 'typescript';
  if (filePath.endsWith('.jsx')) return 'jsx';
  if (filePath.endsWith('.js')) return 'javascript';
  if (filePath.endsWith('.py')) return 'python';
  if (filePath.endsWith('.go')) return 'go';
  if (filePath.endsWith('.rs')) return 'rust';
  if (filePath.endsWith('.java')) return 'java';
  if (filePath.endsWith('.c') || filePath.endsWith('.h')) return 'c';
  if (filePath.endsWith('.cpp') || filePath.endsWith('.cc') || filePath.endsWith('.hpp')) return 'cpp';

  return 'unknown';
}

/**
 * Batch create anchors from file with multiple byte ranges
 */
export function createEditAnchorsFromFile(
  filePath: string,
  ranges: Array<{ startByte: number; endByte: number }>,
  sourceRevision: number = 0
): AstEditAnchor[] {
  try {
    const content = readFileSync(filePath, 'utf-8');
    return ranges
      .map(range =>
        createEditAnchor(filePath, range.startByte, range.endByte, content, sourceRevision)
      )
      .filter((anchor): anchor is AstEditAnchor => anchor !== null);
  } catch (error) {
    console.error(`Failed to batch create anchors for ${filePath}:`, error);
    return [];
  }
}

/**
 * Validate an existing anchor against current file state
 */
export function validateAnchor(anchor: AstEditAnchor): boolean {
  try {
    const content = readFileSync(anchor.filePath, 'utf-8');
    const normalized = normalizeLineEndings(content);

    // Check byte range validity
    if (anchor.startByte < 0 || anchor.endByte > normalized.length || anchor.startByte > anchor.endByte) {
      return false;
    }

    // Check source hash (file has changed)
    const currentSourceHash = hashContent(normalized);
    if (currentSourceHash !== anchor.sourceHash) {
      return false;
    }

    // Check node hash (exact content preserved)
    const currentNodeText = extractNodeText(normalized, anchor.startByte, anchor.endByte);
    const currentNodeHash = hashContent(anchor.nodeKind + '|' + normalizeLineEndings(currentNodeText));
    if (currentNodeHash !== anchor.nodeHash) {
      return false;
    }

    return anchor.parseValid;
  } catch (error) {
    console.error(`Failed to validate anchor ${anchor.anchorId}:`, error);
    return false;
  }
}
