import { pgTable, serial, text, integer, boolean, timestamp, jsonb, numeric, index, uuid } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

export const workspaceTasks = pgTable('workspace_tasks', {
  id: serial('id').primaryKey(),
  title: text('title'),
  name: text('name'),
  workspace_id: text('workspace_id'),
  workspaceId: text('workspace_id'),
  feature_id: text('feature_id'),
});

export const taskSemanticPackets = pgTable('task_semantic_packets', {
  id: serial('id').primaryKey().notNull(),
  point_kind: text('point_kind').notNull().default('task_summary'),
  packet_key: text('packet_key'),
  qdrant_point_id: text('qdrant_point_id'),
  workspace_id: text('workspace_id'),
  workspace_task_id: integer('workspace_task_id'),
  feature_id: text('feature_id'),
  feature_label: text('feature_label'),
  alias_id: text('alias_id'),
  source_ref: text('source_ref'),
  canonical_source_ref: text('canonical_source_ref'),
  source_ref_hash: text('source_ref_hash'),
  file_path: text('file_path'),
  semantic_path: jsonb('semantic_path').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
  related_feature_ids: jsonb('related_feature_ids').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
  related_task_ids: jsonb('related_task_ids').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
  related_file_paths: jsonb('related_file_paths').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
  cluster_id: text('cluster_id'),
  centroid_id: text('centroid_id'),
  parent_centroid_id: text('parent_centroid_id'),
  community_id: integer('community_id'),
  community_source: text('community_source'),
  community_confidence: numeric('community_confidence'),
  metadata: jsonb('metadata').notNull().default(sql`'{}'::jsonb`),
  tags: jsonb('tags').$type<string[]>().notNull().default(sql`'[]'::jsonb`),
  summary: text('summary'),
  summary_llm: text('summary_llm'),
  summary_model: text('summary_model'),
  next_action: text('next_action'),
  summary_hash: text('summary_hash'),
  confidence: text('confidence'),
  lineage_version: text('lineage_version'),
  ledger_type: text('ledger_type'),
  canonical: boolean('canonical').notNull().default(false),
  payload_backfilled_at: timestamp('payload_backfilled_at', { withTimezone: true }),
  domain_class: text('domain_class'),
  som_row: integer('som_row'),
  som_col: integer('som_col'),
  som_index: integer('som_index'),
  kmeans_cluster: integer('kmeans_cluster'),
  status: text('status').notNull().default('todo'),
  agent_pickup_ready: boolean('agent_pickup_ready').notNull().default(false),
  observed_at: timestamp('observed_at', { withTimezone: true }).defaultNow().notNull(),
  valid_from: timestamp('valid_from', { withTimezone: true }).defaultNow().notNull(),
  valid_to: timestamp('valid_to', { withTimezone: true }),
  created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updated_at: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  deleted: boolean('deleted').notNull().default(false),
}, (table) => ({
  agentPickupReadyIdx: index('idx_task_semantic_packets_agent_pickup_ready').on(table.agent_pickup_ready),
  aliasIdIdx: index('task_semantic_packets_alias_id_idx').on(table.alias_id),
  centroidIdIdx: index('idx_task_semantic_packets_centroid_id').on(table.centroid_id),
  clusterIdIdx: index('idx_task_semantic_packets_cluster_id').on(table.cluster_id),
  createdAtIdx: index('idx_task_semantic_packets_created_at').on(table.created_at),
  packetKeyIdx: index('idx_task_semantic_packets_packet_key_idx').on(table.packet_key),
  featureIdIdx: index('idx_task_semantic_packets_feature_id').on(table.feature_id),
  featureIdAliasIdx: index('idx_task_semantic_packets_feature_id_idx').on(table.feature_id),
  featureLabelIdx: index('idx_task_semantic_packets_feature_label_idx').on(table.feature_label),
  communityIdIdx: index('idx_task_semantic_packets_community_id_idx').on(table.community_id),
  communitySourceIdx: index('idx_task_semantic_packets_community_source_idx').on(table.community_source),
  communityConfidenceIdx: index('idx_task_semantic_packets_community_confidence_idx').on(table.community_confidence),
  metadataGin: index('idx_task_semantic_packets_metadata_gin').using('gin', table.metadata),
  pointKindIdx: index('idx_task_semantic_packets_point_kind').on(table.point_kind),
  qdrantPointIdIdx: index('idx_task_semantic_packets_qdrant_point_id').on(table.qdrant_point_id),
  relatedFeatureIdsGin: index('idx_task_semantic_packets_related_feature_ids_gin').using('gin', table.related_feature_ids),
  relatedFilePathsGin: index('idx_task_semantic_packets_related_file_paths_gin').using('gin', table.related_file_paths),
  relatedTaskIdsGin: index('idx_task_semantic_packets_related_task_ids_gin').using('gin', table.related_task_ids),
  semanticPathGin: index('idx_task_semantic_packets_semantic_path_gin').using('gin', table.semantic_path),
  sourceRefIdx: index('idx_task_semantic_packets_source_ref').on(table.source_ref),
  sourceRefAliasIdx: index('idx_task_semantic_packets_source_ref_idx').on(table.source_ref),
  sourceRefHashIdx: index('tsp_source_ref_hash_idx').on(table.source_ref_hash),
  lineageVersionIdx: index('idx_task_semantic_packets_lineage_version_idx').on(table.lineage_version),
  ledgerTypeIdx: index('idx_task_semantic_packets_ledger_type_idx').on(table.ledger_type),
  domainClassIdx: index('idx_task_semantic_packets_domain_class_idx').on(table.domain_class),
  somRowIdx: index('idx_task_semantic_packets_som_row_idx').on(table.som_row),
  somColIdx: index('idx_task_semantic_packets_som_col_idx').on(table.som_col),
  somIndexIdx: index('idx_task_semantic_packets_som_index_idx').on(table.som_index),
  kmeansClusterIdx: index('idx_task_semantic_packets_kmeans_cluster_idx').on(table.kmeans_cluster),
  tagsGin: index('idx_task_semantic_packets_tags_gin').using('gin', table.tags),
  statusIdx: index('idx_task_semantic_packets_status').on(table.status),
  updatedAtIdx: index('idx_task_semantic_packets_updated_at').on(table.updated_at),
  workspaceIdIdx: index('idx_task_semantic_packets_workspace_id').on(table.workspace_id),
  workspaceTaskIdIdx: index('idx_task_semantic_packets_workspace_task_id').on(table.workspace_task_id),
}));

export const agentPickupQueue = pgTable('agent_pickup_queue', {
  id: serial('id').primaryKey(),
  task_id: text('task_id'),
  packet_id: text('packet_id'),
  status: text('status'),
  lane: text('lane').notNull().default('semantic_packet'),
  picked_up_at: timestamp('picked_up_at'),
  completed_at: timestamp('completed_at'),
  available_at: timestamp('available_at'),
  created_at: timestamp('created_at'),
  updated_at: timestamp('updated_at'),
  attempts: integer('attempts'),
  max_attempts: integer('max_attempts'),
  error: text('error'),
});

export const taskFileLinks = pgTable('task_file_links', {
  id: serial('id').primaryKey(),
  workspace_task_id: integer('workspace_task_id'),
  file_path: text('file_path'),
  created_at: timestamp('created_at'),
});

export const taskClusterLinks = pgTable('task_cluster_links', {
  id: uuid('id').primaryKey().defaultRandom(),
  workspace_task_id: integer('workspace_task_id').notNull(),
  feature_id: text('feature_id'),
  qdrant_point_id: text('qdrant_point_id').notNull(),
  cluster_id: text('cluster_id'),
  centroid_id: text('centroid_id'),
  relation_kind: text('relation_kind').notNull().default('related'),
  source_ref: text('source_ref'),
  created_at: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, (table) => ({
  taskIdx: index('idx_task_cluster_links_task_id').on(table.workspace_task_id),
  featureIdx: index('idx_task_cluster_links_feature_id').on(table.feature_id),
  clusterIdx: index('idx_task_cluster_links_cluster_id').on(table.cluster_id),
  centroidIdx: index('idx_task_cluster_links_centroid_id').on(table.centroid_id),
}));
