/**
 * atlas-cartridge-seeds.ts
 *
 * Read-only adapter: loads parent atlas seed tiles for codebase-context queries.
 *
 * Guardrails (hard):
 *   - NEVER reads case/evidence cartridge data
 *   - NEVER writes to Qdrant, Redis, or DB
 *   - ONLY injected when retrieval_mode is explicitly codebase-context
 *   - ONLY used when upstream tiers (Qdrant ANN + Postgres FTS) return nothing
 *   - Seeds scored at 0.25× — below Qdrant (1.0×) and FTS (0.3×)
 *   - File is regeneratable build artifact at .tmp/atlas-cartridge-seeds.jsonl
 */

import fs from 'node:fs';
import path from 'node:path';

export interface AtlasSeedTile {
  seed_id: string;
  tile_type: 'codebase_atlas_tile';
  retrieval_mode: 'atlas_seed_for_chr97';
  source: 'parent_atlas';
  sourceRef: string;
  feature_label: string;
  status?: string;
  hot_keywords: string[];
  dependencies: string[];
  routes: string[];
  mcp_tools: string[];
  db_tables: string[];
  qdrant_tags: string[];
  redis_hint_key: string;
  risk_notes: string;
  nextAction: string;
}

// Path is relative to the repo root — resolved at module load time
const SEEDS_PATH = path.resolve(
  process.cwd(),
  '..',
  '.tmp',
  'atlas-cartridge-seeds.jsonl'
);

// Simple in-process cache — seeds file rarely changes (regenerated by atlas pipeline)
let _cache: AtlasSeedTile[] | null = null;
let _cacheMtime = 0;

function loadSeeds(): AtlasSeedTile[] {
  try {
    if (!fs.existsSync(SEEDS_PATH)) return [];
    const stat = fs.statSync(SEEDS_PATH);
    if (_cache && stat.mtimeMs === _cacheMtime) return _cache;
    const lines = fs.readFileSync(SEEDS_PATH, 'utf8').split('\n').filter(Boolean);
    _cache = lines.map((l) => JSON.parse(l) as AtlasSeedTile);
    _cacheMtime = stat.mtimeMs;
    return _cache;
  } catch {
    return [];
  }
}

/**
 * Score a seed against a query by keyword overlap.
 * Returns 0 if no overlap — caller filters these out.
 */
function scoreSeed(seed: AtlasSeedTile, queryTokens: Set<string>): number {
  const seedTokens = new Set([
    ...seed.hot_keywords.map((k) => k.toLowerCase()),
    ...seed.feature_label.toLowerCase().split(/\W+/),
  ]);
  let hits = 0;
  for (const t of queryTokens) {
    if (seedTokens.has(t)) hits++;
  }
  if (!hits) return 0;
  // Normalise: max score 0.25 (below Qdrant 1.0× and FTS 0.3×)
  return Math.min(0.25, (hits / Math.max(queryTokens.size, 1)) * 0.5);
}

function tokenise(text: string): Set<string> {
  return new Set(
    text
      .toLowerCase()
      .split(/\W+/)
      .filter((t) => t.length > 2)
  );
}

export interface AtlasSeedMatch {
  filePath: string;
  content: string;
  score: number;
  tags: string[];
  gpuCluster: null;
  pageRankScore: null;
  routeType: null;
  hasAuthGuard: null;
  somCluster: null;
  somBmuRow: null;
  somBmuCol: null;
  graphAuthorityScore: null;
  _atlasSource: true;
}

/**
 * Query atlas cartridge seeds for a codebase-context query.
 *
 * @param query        - the user query
 * @param limit        - max results (default 6)
 * @returns            - ranked seed matches or empty array
 */
export function queryAtlasSeeds(query: string, limit = 6): AtlasSeedMatch[] {
  const seeds = loadSeeds();
  if (!seeds.length) return [];

  const tokens = tokenise(query);
  if (!tokens.size) return [];

  const scored: Array<{ seed: AtlasSeedTile; score: number }> = [];
  for (const seed of seeds) {
    const score = scoreSeed(seed, tokens);
    if (score > 0) scored.push({ seed, score });
  }

  scored.sort((a, b) => b.score - a.score);

  return scored.slice(0, limit).map(({ seed, score }) => ({
    filePath: seed.sourceRef,
    content: [
      `## ${seed.feature_label}`,
      seed.risk_notes ? `> ${seed.risk_notes}` : '',
      seed.routes.length ? `Routes: ${seed.routes.join(', ')}` : '',
      seed.db_tables.length ? `Tables: ${seed.db_tables.join(', ')}` : '',
      seed.mcp_tools.length ? `MCP tools: ${seed.mcp_tools.join(', ')}` : '',
      seed.nextAction ? `Next: ${seed.nextAction}` : '',
    ]
      .filter(Boolean)
      .join('\n'),
    score,
    tags: [...seed.qdrant_tags, 'source:parent_atlas', 'tile_type:codebase_atlas_tile'],
    gpuCluster: null,
    pageRankScore: null,
    routeType: null,
    hasAuthGuard: null,
    somCluster: null,
    somBmuRow: null,
    somBmuCol: null,
    graphAuthorityScore: null,
    _atlasSource: true as const,
  }));
}

/** Returns true if the seeds file exists and has content. */
export function atlasSeedsAvailable(): boolean {
  return loadSeeds().length > 0;
}