import { describe, expect, it } from 'vitest';
import { aggregateDirectoryProfilesV1, aggregateFileProfileV1, buildChunkRetrievalProfileV1, toCandidateProjectionInputV1, type ChunkRetrievalProfileV1 } from './chunk-retrieval-profile-v1.js';

const chunk = (path: string, id: string, domain = 'retrieval'): ChunkRetrievalProfileV1 => ({ canonicalChunkId: id, packetKey: `packet:${id}`, repositoryId: 'repo:root', repositoryRelativePath: path, sourceRef: `src:${path}`, workspaceRevision: 'sha256:workspace', sourceRevision: `sha256:${id}`, keywords: ['search', 'search'], identifiers: [], nouns: [], astPath: [], calls: [], imports: ['a'], exports: [], semanticTags: ['code'], embeddingRepresentation: 'semantic_768', primaryDomain: domain, domainConfidence: 1, topicIds: ['vector'], conceptIds: ['concept:qdrant'], entityIds: [], ontologyTupleIds: [], featureRevision: 'feature:v1' });

describe('Chunk/File/Directory retrieval profiles', () => {
  it('aggregates a file without changing canonical identities', () => { const result = aggregateFileProfileV1([chunk('src/retrieval/a.ts', 'c1'), { ...chunk('src/retrieval/a.ts', 'c2', 'graph'), sourceRevision: 'sha256:c1', packetKey: 'packet:c1' }]); expect(result.fileKey).toBe('repo:root:src/retrieval/a.ts'); expect(result.chunkIds).toEqual(['c1', 'c2']); expect(result.keywords).toEqual(['search']); expect(result.domains).toHaveLength(2); });
  it('groups directories by repository and preserves workspace revision', () => { const result = aggregateDirectoryProfilesV1([chunk('src/retrieval/a.ts', 'c1'), chunk('src/graph/b.ts', 'c2')]); expect(result.map((item) => item.path)).toEqual(['src/graph', 'src/retrieval']); expect(result.every((item) => item.workspaceRevision === 'sha256:workspace')).toBe(true); expect(result.every((item) => /^[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(item.directoryId))).toBe(true); expect(result[0].directoryId).toBe(aggregateDirectoryProfilesV1([chunk('src/retrieval/a.ts', 'c1'), chunk('src/graph/b.ts', 'c2')])[0].directoryId); });
  it('rejects mixed feature revisions inside one directory', () => { expect(() => aggregateDirectoryProfilesV1([chunk('src/a.ts', 'c1'), { ...chunk('src/b.ts', 'c2'), featureRevision: 'feature:v2' }])).toThrow(/mixed feature revisions/); });
  it('coalesces Windows and POSIX separators for one file directory', () => { const result = aggregateDirectoryProfilesV1([chunk('src\\retrieval\\a.ts', 'c1'), chunk('src/retrieval/b.ts', 'c2')]); expect(result).toHaveLength(1); expect(result[0].path).toBe('src/retrieval'); });
  it('rejects mixed file identity or revisions', () => { expect(() => aggregateFileProfileV1([chunk('src/a.ts', 'c1'), { ...chunk('src/b.ts', 'c2'), repositoryRelativePath: 'src/b.ts' }])).toThrow(/identity or revision/); });
  it('rejects duplicate chunks and mixed packet identities', () => { expect(() => aggregateFileProfileV1([chunk('src/a.ts', 'c1'), chunk('src/a.ts', 'c1')])).toThrow(/duplicate/); expect(() => aggregateFileProfileV1([chunk('src/a.ts', 'c1'), { ...chunk('src/a.ts', 'c2'), sourceRevision: 'sha256:c1', packetKey: 'packet:other' }])).toThrow(/packet identity/); });
  it('rejects mixed workspace authority inside a directory', () => { expect(() => aggregateDirectoryProfilesV1([chunk('src/a.ts', 'c1'), { ...chunk('src/b.ts', 'c2'), workspaceRevision: 'sha256:other' }])).toThrow(/workspace revision/); });
  it('projects only present profile evidence into the existing candidate matrix shape', () => { const result = toCandidateProjectionInputV1(chunk('src/a.ts', 'c1'), 'sha256:c1'); expect(result).toMatchObject({ packet_key: 'packet:c1', summary_provenance: undefined, dependency_fanout: 1, feature_label_confidence: 1, source_revision_match: 1 }); });
  it('requires exact canonical chunk and proven lineage identity', () => { const result = buildChunkRetrievalProfileV1({ chunk: { chunk_id: 'c1', relative_path: 'src/a.ts', source_ref: 'src/a.ts', ast_imports: ['x'] }, lineage: { packet_key: 'packet:c1', canonical_chunk_id: 'c1', source_ref: 'src/a.ts', source_namespace: 'repo:root', source_revision: 'sha256:file', revision_status: 'PROVEN' }, repositoryId: 'repo:root', workspaceRevision: 'sha256:workspace', featureRevision: 'feature:v1' }); expect(result.canonicalChunkId).toBe('c1'); expect(result.sourceRevision).toBe('sha256:file'); expect(result.imports).toEqual(['x']); expect(() => buildChunkRetrievalProfileV1({ chunk: { chunk_id: 'c2', relative_path: 'src/a.ts', source_ref: 'src/a.ts' }, lineage: { packet_key: 'packet:c1', canonical_chunk_id: 'c1', source_ref: 'src/a.ts', source_revision: 'sha256:file', source_namespace: 'repo:root', revision_status: 'PROVEN' }, repositoryId: 'repo:root', workspaceRevision: 'sha256:workspace', featureRevision: 'feature:v1' })).toThrow(/identity/); });
});
