import { traceGraph } from '$lib/server/observability/langfuse.js';
import { extractEntitiesNative } from '../langextract/native.js';
import fs from 'node:fs';
import path from 'node:path';

export interface RerankSignals {
	gemmaScore: number;
	marcoScore?: number;
	langScore?: number;
	wikiScore?: number;
	activityScore?: number;
	finalScore: number;
}

// Default weights
const DEFAULT_WEIGHTS = {
	gemma: 0.35,
	marco: 0.15,
	lang:  0.15,
	wiki:  0.25,
	activity: 0.1
};

/**
 * Load dynamic weights from config file if present.
 * These are generated by scripts/ace-policy-synthesis.ts
 */
function loadWeights() {
	try {
		// Using relative path from src/lib/server/retrieval to src/lib/server/config
		const configPath = path.resolve(process.cwd(), 'src/lib/server/config/rerank-weights.json');
		if (fs.existsSync(configPath)) {
			const data = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
			return { ...DEFAULT_WEIGHTS, ...data };
		}
	} catch (err) {
		// Fallback to defaults
	}
	return DEFAULT_WEIGHTS;
}

/**
 * Calculate LangExtract density score.
 */
export function calculateLangScore(text: string): number {
	const entities = extractEntitiesNative(text);
	const score = 0.5 + (entities.length * 0.05);
	return Math.min(1.0, score);
}

/**
 * Combine multiple rerank signals into a single unified score.
 */
export async function combineRerankSignals(
	query: string,
	signals: Omit<RerankSignals, 'finalScore'>,
	content?: string
): Promise<RerankSignals> {
	return traceGraph('rerank:decision-tree', { query, signals }, async () => {
		let langScore = signals.langScore;
		if (langScore === undefined && content) {
			langScore = calculateLangScore(content);
		}

		const weights = loadWeights();
		
		const finalScore = 
			(signals.gemmaScore * weights.gemma) +
			((signals.marcoScore ?? 0.5) * weights.marco) +
			((langScore ?? 0.5) * weights.lang) +
			((signals.wikiScore ?? 0.5) * weights.wiki) +
			((signals.activityScore ?? 0.0) * (weights.activity ?? 0.0));

		return {
			...signals,
			langScore,
			finalScore
		};
	});
}

export function emitRerankTrace(
	query: string,
	documentId: string,
	signals: RerankSignals,
	metadata: Record<string, any> = {}
) {
	console.log(`[rerank-trace] ${query} -> ${documentId}:`, signals);
}
