import { traceGraph } from '$lib/server/observability/langfuse.js';
import { extractEntitiesNative } from '../langextract/native.js';
import { ENV } from '$lib/server/env.server.js';
import fs from 'node:fs';
import path from 'node:path';

export interface RerankSignals {
	gemmaScore: number;
	marcoScore?: number;
	crossEncoderScore?: number;
	langScore?: number;
	wikiScore?: number;
	activityScore?: number;
	/** f8: 64d cosine similarity between query encoding and doc encoding. */
	encodedSimilarity?: number;
	/** GRPO reward signal: query's top cluster matched this doc's som_cluster. */
	encodedClusterHit?: boolean;
	pagerankScore?: number;
	finalScore: number;
}

// Default weights — must sum to 1.0 (approximated based on user config)
const DEFAULT_WEIGHTS = {
	gemma:    0.30,
  crossEncoder: 0.10,
	lang:     0.10,
	wiki:     0.15,
	activity: 0.05,
	encoded:  0.15,
	pagerank: 0.15,
};

/**
 * Load dynamic weights from config file if present.
 * These are generated by scripts/ace-policy-synthesis.ts
 * Cached with 60-second TTL to avoid repeated filesystem I/O on hot path
 */
let cachedWeights: Record<string, number> | null = null;
let cachedAt = 0;

function loadWeights() {
	const now = Date.now();
	if (cachedWeights && now - cachedAt < 60000) {
		return cachedWeights;
	}

	try {
		// Using relative path from src/lib/server/retrieval to src/lib/server/config
		const configPath = path.resolve(process.cwd(), 'src/lib/server/config/rerank-weights.json');
		if (fs.existsSync(configPath)) {
			const data = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
      const merged = { ...DEFAULT_WEIGHTS, ...data } as Record<string, number>;
      if (merged.marco !== undefined && merged.crossEncoder === undefined) {
        merged.crossEncoder = merged.marco;
      }
      cachedWeights = merged;
      cachedAt = now;
      return merged;
		}
	} catch (err) {
		// Fallback to defaults
	}
	cachedWeights = { ...DEFAULT_WEIGHTS };
	cachedAt = now;
	return cachedWeights;
}

/**
 * Calculate LangExtract density score.
 */
export function calculateLangScore(text: string): number {
	const entities = extractEntitiesNative(text);
	const score = 0.5 + (entities.length * 0.05);
	return Math.min(1.0, score);
}

/**
 * Combine multiple rerank signals into a single unified score.
 */
export async function combineRerankSignals(
	query: string,
	signals: Omit<RerankSignals, 'finalScore'>,
	content?: string
): Promise<RerankSignals> {
	return traceGraph('rerank:decision-tree', { query, signals }, async () => {
		let langScore = signals.langScore;
		if (langScore === undefined && content) {
			langScore = calculateLangScore(content);
		}

		const weights = loadWeights();
		if (ENV.ACE_ENCODED_RERANK_ENABLED) {
			weights.encoded = ENV.ACE_ENCODED_RERANK_WEIGHT;
		}

		const finalScore =
			(signals.gemmaScore * weights.gemma) +
			((signals.crossEncoderScore ?? signals.marcoScore ?? 0.5) * (weights.crossEncoder ?? weights.marco ?? 0.10)) +
			((langScore ?? 0.5) * weights.lang) +
			((signals.wikiScore ?? 0.5) * weights.wiki) +
			((signals.activityScore  ?? 0.0) * (weights.activity ?? 0.0)) +
			((signals.encodedSimilarity ?? 0.0) * (weights.encoded  ?? 0.0)) +
			((signals.pagerankScore ?? 0.0) * (weights.pagerank ?? 0.15));

		return {
			...signals,
			langScore,
			finalScore
		};
	});
}

export function emitRerankTrace(
	query: string,
	documentId: string,
	signals: RerankSignals,
	metadata: Record<string, any> = {}
) {
	console.log(`[rerank-trace] ${query} -> ${documentId}:`, signals);
}
