"""ONTO-PY-01: TS OntologyLinkedTupleV1 -> Python typed representation ->
canonical checksum parity.

Loads the frozen fixture generated by
scripts/atlas/generate-ontology-linked-tuple-fixture-v1.mts (validated
against the REAL TS Zod schema at generation time, not hand-written),
round-trips it through the Python typed dataclasses in models.py, and
proves the round-trip is lossless: same tuple id, same participant
roles/order (the specific thing a naive tuple-flattening would lose),
same evidence refs, same checksum after the stated None-dropping
normalization.

Usage: python python/parent_atlas_ontology/onto_py_01_parity_check.py
Writes: docs/reports/ontology-linked-tuple-python-adapter-parity-v1.json
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from parent_atlas_ontology.checksum import sha256_hex  # noqa: E402
from parent_atlas_ontology.models import OntologyLinkedTupleV1  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE_PATH = REPO_ROOT / "docs" / "reports" / "fixtures" / "ontology-linked-tuple-fixture-v1.json"
REPORT_PATH = REPO_ROOT / "docs" / "reports" / "ontology-linked-tuple-python-adapter-parity-v1.json"


def main() -> int:
    started = time.time()
    raw = json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))

    tuple_obj = OntologyLinkedTupleV1.from_dict(raw)
    round_tripped = tuple_obj.to_dict()

    checks: list[dict] = []

    def check(name: str, ok: bool, detail: str = "") -> None:
        checks.append({"name": name, "ok": ok, "detail": detail})

    check("tuple_id_preserved", round_tripped["tupleId"] == raw["tupleId"], round_tripped["tupleId"])
    check(
        "participant_count_preserved",
        len(round_tripped["participants"]) == len(raw["participants"]) == 4,
        f"expected 4 (genuine n-ary), got {len(round_tripped['participants'])}",
    )
    check(
        "participant_roles_and_order_preserved",
        [p["role"] for p in round_tripped["participants"]] == [p["role"] for p in raw["participants"]],
        str([p["role"] for p in round_tripped["participants"]]),
    )
    check(
        "participant_entity_ids_preserved",
        [p["entityId"] for p in round_tripped["participants"]] == [p["entityId"] for p in raw["participants"]],
        str([p["entityId"] for p in round_tripped["participants"]]),
    )
    check("evidence_refs_preserved", round_tripped["evidenceRefs"] == raw["evidenceRefs"], str(round_tripped["evidenceRefs"]))
    check("confidence_preserved", round_tripped["confidence"] == raw["confidence"], str(round_tripped["confidence"]))
    check(
        "provenance_source_tables_preserved",
        round_tripped["provenance"]["sourceTables"] == raw["provenance"]["sourceTables"],
        str(round_tripped["provenance"]["sourceTables"]),
    )

    raw_checksum = sha256_hex(raw)
    round_trip_checksum = sha256_hex(round_tripped)
    check(
        "canonical_checksum_parity_after_none_normalization",
        raw_checksum == round_trip_checksum,
        f"raw={raw_checksum} round_trip={round_trip_checksum}",
    )

    all_ok = all(c["ok"] for c in checks)
    duration_ms = round((time.time() - started) * 1000, 2)

    report = {
        "gate": "ONTO-PY-01",
        "description": "TS OntologyLinkedTupleV1 fixture -> Python typed representation -> canonical checksum parity",
        "fixturePath": str(FIXTURE_PATH.relative_to(REPO_ROOT)).replace("\\", "/"),
        "checksumNormalization": "None-valued keys dropped before hashing on both sides (see checksum.py docstring) - a stated semantic-equivalence normalization, not a byte-identical JSON claim",
        "checks": checks,
        "pass": all_ok,
        "durationMs": duration_ms,
        "writesPerformed": False,
    }

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    print(f"ONTO-PY-01: {'PASS' if all_ok else 'FAIL'}")
    for c in checks:
        print(f"  [{'x' if c['ok'] else ' '}] {c['name']}: {c['detail']}")
    print(f"Report written: {REPORT_PATH}")

    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
