CREATE TABLE "retrieval_telemetry" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "retrieval_telemetry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"query" text NOT NULL,
	"query_hash" text NOT NULL,
	"latency_ms" integer NOT NULL,
	"vector_hits" integer DEFAULT 0 NOT NULL,
	"trigram_hits" integer DEFAULT 0 NOT NULL,
	"fts_hits" integer DEFAULT 0 NOT NULL,
	"selected_packet_key" text,
	"selected_packet_keys" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"selected_feature_id" text,
	"feature_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"fusion_score" real,
	"cache_hit" boolean DEFAULT false NOT NULL,
	"surface" text NOT NULL,
	"environment" text NOT NULL,
	"retrieval_strategy" text DEFAULT 'hybrid' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "packet_markdown_chunks" (
	"id" serial PRIMARY KEY NOT NULL,
	"packet_key" text NOT NULL,
	"chunk_index" integer NOT NULL,
	"markdown_content" text NOT NULL,
	"ts_vector" "tsvector",
	"created_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "atlas_feature_map" ADD COLUMN "packet_id" text;--> statement-breakpoint
CREATE INDEX "idx_retrieval_telemetry_created_at" ON "retrieval_telemetry" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_retrieval_telemetry_query_hash" ON "retrieval_telemetry" USING btree ("query_hash");--> statement-breakpoint
CREATE INDEX "idx_retrieval_telemetry_surface" ON "retrieval_telemetry" USING btree ("surface");--> statement-breakpoint
CREATE INDEX "idx_retrieval_telemetry_environment" ON "retrieval_telemetry" USING btree ("environment");--> statement-breakpoint
CREATE INDEX "idx_retrieval_telemetry_packet_key" ON "retrieval_telemetry" USING btree ("selected_packet_key");--> statement-breakpoint
CREATE INDEX "idx_retrieval_telemetry_packet_keys_gin" ON "retrieval_telemetry" USING gin ("selected_packet_keys");--> statement-breakpoint
CREATE INDEX "idx_retrieval_telemetry_feature_id" ON "retrieval_telemetry" USING btree ("selected_feature_id");--> statement-breakpoint
CREATE INDEX "idx_retrieval_telemetry_feature_ids_gin" ON "retrieval_telemetry" USING gin ("feature_ids");--> statement-breakpoint
CREATE INDEX "idx_retrieval_telemetry_latency_ms" ON "retrieval_telemetry" USING btree ("latency_ms");--> statement-breakpoint
CREATE INDEX "idx_retrieval_telemetry_strategy" ON "retrieval_telemetry" USING btree ("retrieval_strategy");--> statement-breakpoint
CREATE INDEX "packet_markdown_chunks_packet_key_idx" ON "packet_markdown_chunks" USING btree ("packet_key");--> statement-breakpoint
CREATE UNIQUE INDEX "packet_markdown_chunks_key_chunk_idx" ON "packet_markdown_chunks" USING btree ("packet_key","chunk_index");--> statement-breakpoint
CREATE INDEX "packet_markdown_chunks_ts_vector_idx" ON "packet_markdown_chunks" USING gin ("ts_vector");--> statement-breakpoint
CREATE INDEX "packet_markdown_chunks_markdown_content_trgm_idx" ON "packet_markdown_chunks" USING gin ("markdown_content");