/**
 * vault-walker.tool.ts — read-only MCP tools for the Obsidian codebase vault.
 *
 * Vault layout (generated by scripts/graphify-obsidian-vault.mjs):
 *   docs/obsidian-vault/
 *     ├── Files/<slug>.md         (file notes with frontmatter + Breadcrumbs typed edges)
 *     ├── Clusters/cluster-N.md   (cluster notes with pagerank_sum, risk, contains, same)
 *     ├── Indexes/*.md            (dataview index notes — high-risk, low-conf, etc.)
 *     ├── agent-manifest.json     (read-only contract — read on init)
 *     ├── codebase.canvas         (full spatial map)
 *     └── kg.canvas               (cluster↔cluster typed-edge subgraph)
 *
 * Policy contract (from agent-manifest.json):
 *   read_only: true
 *   forbidden_actions: patch_code, mutate_qdrant/postgres/redis/neo4j,
 *                      rewrite_vault, execute_shell
 *
 * 7 tools shipped (all read-only):
 *   vault.search         — keyword + frontmatter filter across notes
 *   vault.read           — read one note, parse frontmatter + body sections
 *   vault.followLinks    — typed-edge traversal (up/same/imports/contains)
 *   vault.resolveEmbedding — return Qdrant embedding_id from a file path
 *   retrieval.qdrantLookup — fetch Qdrant payload by embedding_id
 *   agent.explainCluster — synthesize cluster overview from cluster note + members
 *   agent.proposeFix     — generate a markdown fix proposal (returns string, NO writes)
 */

import { z } from 'zod';
import { readFile, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve, join, basename } from 'node:path';

// ── Vault root ─────────────────────────────────────────────────────────────
const REPO_ROOT = resolve(process.cwd());
const VAULT_DIR = process.env.OBSIDIAN_VAULT_DIR
  ?? resolve(REPO_ROOT, 'docs/obsidian-vault');

// ── Slug helper (must match generator) ─────────────────────────────────────
const slug = (p: string) => String(p)
  .replace(/\\/g, '/')
  .replace(/[^\w/.-]+/g, '_')
  .replace(/\//g, '__')
  .replace(/\.\w+$/, '')
  .toLowerCase()
  .slice(0, 180);

// ── Frontmatter parser (YAML subset — strings, numbers, booleans, arrays) ──
interface NoteFrontmatter {
  type?: string;
  path?: string;
  clusterId?: number;
  cluster_id?: string;
  topic?: string;
  pagerank?: number;
  pagerank_sum?: number;
  pagerank_max?: number;
  blend?: number;
  risk?: 'low' | 'medium' | 'high';
  confidence?: 'low' | 'medium' | 'high';
  embedding_id?: string;
  top_tags?: string[];
  tags?: string[];
  aliases?: string[];
  up?: string[];
  same?: string[];
  imports?: string[];
  contains?: string[];
  [k: string]: unknown;
}

function parseFrontmatter(md: string): { fm: NoteFrontmatter; body: string } {
  const m = md.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) return { fm: {}, body: md };
  const fm: NoteFrontmatter = {};
  for (const line of m[1].split('\n')) {
    const kv = line.match(/^([\w-]+):\s*(.*)$/);
    if (!kv) continue;
    const [, k, raw] = kv;
    const v = raw.trim();
    if (!v) { fm[k] = ''; continue; }
    try {
      fm[k] = JSON.parse(v);                              // arrays / strings / numbers / bools
    } catch {
      fm[k] = v.replace(/^["']|["']$/g, '');              // bare string fallback
    }
  }
  return { fm, body: m[2] };
}

// ── Wikilink → vault path resolver ─────────────────────────────────────────
// "[[Files/foo|label]]" → "Files/foo.md"
function resolveWikilink(link: string): string | null {
  const m = link.match(/^\[\[([^|\]]+?)(?:\|[^\]]+)?\]\]$/);
  if (!m) return null;
  const target = m[1].trim();
  return target.endsWith('.md') ? target : `${target}.md`;
}

// ── Note loader (cached per-call) ──────────────────────────────────────────
async function readNote(relPath: string): Promise<{ fm: NoteFrontmatter; body: string; path: string } | null> {
  const full = join(VAULT_DIR, relPath);
  if (!existsSync(full)) return null;
  const md = await readFile(full, 'utf8');
  const { fm, body } = parseFrontmatter(md);
  return { fm, body, path: relPath };
}

// ── Manifest loader ────────────────────────────────────────────────────────
async function readManifest(): Promise<Record<string, unknown> | null> {
  const p = join(VAULT_DIR, 'agent-manifest.json');
  if (!existsSync(p)) return null;
  return JSON.parse(await readFile(p, 'utf8'));
}

// ── 1. vault.search ────────────────────────────────────────────────────────
export const vaultSearchTool = {
  name: 'vault.search',
  description:
    'Search the Obsidian codebase vault by keyword (case-insensitive substring on title + frontmatter + body) with optional frontmatter filters. ' +
    'Read-only. Returns ranked note paths with snippets. Use when investigating which files/clusters relate to a topic before pulling full content.',
  parameters: z.object({
    query: z.string().min(1).describe('Keyword or phrase'),
    collection: z.enum(['Files', 'Clusters', 'Indexes', 'all']).default('all').optional()
      .describe('Limit search to a vault subfolder'),
    risk: z.enum(['low', 'medium', 'high']).optional().describe('Filter clusters by risk'),
    minPagerank: z.number().optional().describe('Filter files by min pagerank'),
    limit: z.number().int().min(1).max(100).default(20).optional(),
  }),
  execute: async (args: { query: string; collection?: string; risk?: string; minPagerank?: number; limit?: number }) => {
    const limit = args.limit ?? 20;
    const dirs = args.collection === 'all'
      ? ['Files', 'Clusters', 'Indexes']
      : [args.collection ?? 'Files'];
    const q = args.query.toLowerCase();
    const hits: Array<{ path: string; score: number; snippet: string; frontmatter: NoteFrontmatter }> = [];

    for (const dir of dirs) {
      const dirPath = join(VAULT_DIR, dir);
      if (!existsSync(dirPath)) continue;
      const files = await readdir(dirPath);
      for (const f of files) {
        if (!f.endsWith('.md')) continue;
        const note = await readNote(`${dir}/${f}`);
        if (!note) continue;

        // frontmatter filters
        if (args.risk && note.fm.risk !== args.risk) continue;
        if (args.minPagerank != null && (note.fm.pagerank ?? 0) < args.minPagerank) continue;

        // score = 3*title-hit + 2*frontmatter-hit + 1*body-hit
        const titleHit  = (note.fm.topic ?? note.fm.path ?? f).toLowerCase().includes(q) ? 3 : 0;
        const fmText    = JSON.stringify(note.fm).toLowerCase();
        const fmHit     = fmText.includes(q) ? 2 : 0;
        const bodyLower = note.body.toLowerCase();
        const bodyHit   = bodyLower.includes(q) ? 1 : 0;
        const score     = titleHit + fmHit + bodyHit;
        if (score === 0) continue;

        const idx = bodyLower.indexOf(q);
        const snippet = idx >= 0
          ? note.body.slice(Math.max(0, idx - 60), idx + q.length + 80).replace(/\n+/g, ' ').trim()
          : (note.fm.topic as string ?? '');

        hits.push({ path: `${dir}/${f}`, score, snippet, frontmatter: note.fm });
      }
    }

    hits.sort((a, b) => b.score - a.score);
    return JSON.stringify({
      query: args.query,
      totalFound: hits.length,
      hits: hits.slice(0, limit),
    });
  },
} as const;

// ── 2. vault.read ──────────────────────────────────────────────────────────
export const vaultReadTool = {
  name: 'vault.read',
  description:
    'Read one Obsidian note. Returns parsed frontmatter, full body, extracted typed edges (up/same/imports/contains), and embedding_id if present. ' +
    'Read-only. Path is relative to vault root, e.g. "Files/src__lib__server__db__client.md" or "Clusters/cluster-7.md".',
  parameters: z.object({
    path: z.string().describe('Vault-relative path to a note (.md)'),
  }),
  execute: async (args: { path: string }) => {
    const note = await readNote(args.path);
    if (!note) return JSON.stringify({ error: 'note_not_found', path: args.path });
    const edges = {
      up:       (note.fm.up       ?? []).map(resolveWikilink).filter(Boolean),
      same:     (note.fm.same     ?? []).map(resolveWikilink).filter(Boolean),
      imports:  (note.fm.imports  ?? []).map(resolveWikilink).filter(Boolean),
      contains: (note.fm.contains ?? []).map(resolveWikilink).filter(Boolean),
    };
    return JSON.stringify({
      path: note.path,
      type: note.fm.type ?? 'unknown',
      frontmatter: note.fm,
      body: note.body,
      edges,
      embedding_id: note.fm.embedding_id ?? null,
    });
  },
} as const;

// ── 3. vault.followLinks ───────────────────────────────────────────────────
export const vaultFollowLinksTool = {
  name: 'vault.followLinks',
  description:
    'Walk the typed-edge graph from a note. edgeType ∈ {up, same, imports, contains}. ' +
    'up=BELONGS_TO_CLUSTER, same=SIMILAR_TOPOLOGY (cluster↔cluster jaccard≥0.3), ' +
    'imports=IMPORTS (file→file local imports), contains=CONTAINS (cluster→members). ' +
    'Read-only. Hops up to 3. Returns each visited note with its type + minimal frontmatter.',
  parameters: z.object({
    path: z.string().describe('Vault-relative starting note'),
    edgeType: z.enum(['up', 'same', 'imports', 'contains']).describe('Typed edge to traverse'),
    hops: z.number().int().min(1).max(3).default(1).optional().describe('Traversal depth'),
    limit: z.number().int().min(1).max(50).default(20).optional().describe('Max nodes returned'),
  }),
  execute: async (args: { path: string; edgeType: 'up' | 'same' | 'imports' | 'contains'; hops?: number; limit?: number }) => {
    const hops = args.hops ?? 1;
    const limit = args.limit ?? 20;
    const visited = new Set<string>();
    const out: Array<{ path: string; type?: string; topic?: string; risk?: string; pagerank?: number; depth: number }> = [];
    let frontier: string[] = [args.path];

    for (let depth = 0; depth <= hops && out.length < limit; depth++) {
      const next: string[] = [];
      for (const p of frontier) {
        if (visited.has(p)) continue;
        visited.add(p);
        const note = await readNote(p);
        if (!note) continue;
        if (depth > 0) {
          out.push({
            path: p,
            type: note.fm.type as string,
            topic: note.fm.topic as string,
            risk: note.fm.risk as string,
            pagerank: note.fm.pagerank as number,
            depth,
          });
          if (out.length >= limit) break;
        }
        const edges = (note.fm[args.edgeType] as string[] | undefined) ?? [];
        for (const e of edges) {
          const resolved = resolveWikilink(e);
          if (resolved && !visited.has(resolved)) next.push(resolved);
        }
      }
      frontier = next;
    }

    return JSON.stringify({
      start: args.path,
      edgeType: args.edgeType,
      hops,
      totalVisited: visited.size - 1,
      nodes: out,
    });
  },
} as const;

// ── 4. vault.resolveEmbedding ──────────────────────────────────────────────
export const vaultResolveEmbeddingTool = {
  name: 'vault.resolveEmbedding',
  description:
    'Resolve a vault note path to its Qdrant embedding_id (qdrant://codebase_chunks_768/<repo-relative-path>). ' +
    'Pair with retrieval.qdrantLookup to fetch the actual chunk vector + payload. Read-only.',
  parameters: z.object({
    path: z.string().describe('Vault-relative note path OR repo-relative source path'),
  }),
  execute: async (args: { path: string }) => {
    // Accept either vault path or raw repo path
    if (args.path.startsWith('Files/')) {
      const note = await readNote(args.path);
      if (!note) return JSON.stringify({ error: 'note_not_found', path: args.path });
      return JSON.stringify({
        path: note.path,
        repo_path: note.fm.path ?? null,
        embedding_id: note.fm.embedding_id ?? null,
        clusterId: note.fm.clusterId ?? null,
      });
    }
    // Raw repo path: synthesize embedding_id from manifest scheme
    const manifest = await readManifest();
    const scheme = (manifest?.retrieval as Record<string, string> | undefined)?.embedding_id_scheme
      ?? 'qdrant://codebase_chunks_768/<path>';
    const id = scheme.replace('<path>', args.path);
    return JSON.stringify({
      repo_path: args.path,
      vault_note: `Files/${slug(args.path)}.md`,
      embedding_id: id,
    });
  },
} as const;

// ── 5. retrieval.qdrantLookup ──────────────────────────────────────────────
export const retrievalQdrantLookupTool = {
  name: 'retrieval.qdrantLookup',
  description:
    'Look up a Qdrant point by embedding_id (qdrant://<collection>/<filter-value>) and return its payload + score. ' +
    'Uses scroll-with-filter on `path` field (no vector required for ID lookup). Read-only.',
  parameters: z.object({
    embedding_id: z.string().describe('embedding_id from vault.resolveEmbedding'),
    limit: z.number().int().min(1).max(20).default(5).optional().describe('Max chunks to return'),
  }),
  execute: async (args: { embedding_id: string; limit?: number }) => {
    const m = args.embedding_id.match(/^qdrant:\/\/([^/]+)\/(.+)$/);
    if (!m) return JSON.stringify({ error: 'invalid_embedding_id', expected: 'qdrant://<collection>/<path>' });
    const [, collection, path] = m;
    const limit = args.limit ?? 5;
    const base = process.env.QDRANT_URL ?? 'http://localhost:6333';
    try {
      const res = await fetch(`${base}/collections/${collection}/points/scroll`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          filter: { must: [{ key: 'path', match: { value: path } }] },
          limit,
          with_payload: true,
          with_vector: false,
        }),
        signal: AbortSignal.timeout(8_000),
      });
      if (!res.ok) return JSON.stringify({ error: `qdrant_${res.status}`, collection, path });
      const json = await res.json() as { result?: { points: Array<{ id: unknown; payload: Record<string, unknown> }> } };
      return JSON.stringify({
        collection,
        path,
        chunks: (json.result?.points ?? []).map(p => ({
          id: String(p.id),
          summary: String(p.payload?.summary ?? p.payload?.content ?? '').slice(0, 400),
          tags: p.payload?.tags ?? [],
          som_cluster: p.payload?.som_cluster ?? null,
        })),
      });
    } catch (e) {
      return JSON.stringify({ error: 'qdrant_unavailable', message: (e as Error).message });
    }
  },
} as const;

// ── 6. agent.explainCluster ────────────────────────────────────────────────
export const agentExplainClusterTool = {
  name: 'agent.explainCluster',
  description:
    'Synthesize a cluster overview: pulls Clusters/cluster-N.md + top-K member files (by pagerank) and returns a structured summary. ' +
    'Read-only. NO LLM call — pure aggregation. The CALLER (agent) generates prose from this.',
  parameters: z.object({
    cluster_id: z.union([z.string(), z.number()]).describe('Cluster ID (e.g. 7 or "cluster-7")'),
    topMembers: z.number().int().min(1).max(20).default(5).optional(),
  }),
  execute: async (args: { cluster_id: string | number; topMembers?: number }) => {
    const id = String(args.cluster_id).replace(/^cluster-/, '');
    const path = `Clusters/cluster-${id}.md`;
    const note = await readNote(path);
    if (!note) return JSON.stringify({ error: 'cluster_not_found', cluster_id: id });

    const topK = args.topMembers ?? 5;
    const containsLinks = ((note.fm.contains ?? []) as string[])
      .map(resolveWikilink).filter(Boolean) as string[];

    const memberSummaries: Array<Record<string, unknown>> = [];
    for (const m of containsLinks.slice(0, topK * 3)) {
      const mNote = await readNote(m);
      if (!mNote) continue;
      memberSummaries.push({
        path: mNote.fm.path ?? m,
        clusterId: mNote.fm.clusterId,
        pagerank: mNote.fm.pagerank ?? 0,
        confidence: mNote.fm.confidence,
        lineCount: mNote.fm.lineCount ?? 0,
        isRoute: mNote.fm.isRoute ?? false,
        hasAuth: mNote.fm.hasAuth ?? false,
      });
    }
    memberSummaries.sort((a, b) => (b.pagerank as number) - (a.pagerank as number));

    return JSON.stringify({
      cluster_id: `cluster-${id}`,
      topic: note.fm.topic,
      risk: note.fm.risk,
      pagerank_sum: note.fm.pagerank_sum,
      pagerank_max: note.fm.pagerank_max,
      member_count: note.fm.memberCount,
      top_tags: note.fm.top_tags ?? [],
      neighbors: ((note.fm.same ?? []) as string[]).map(resolveWikilink).filter(Boolean),
      top_members: memberSummaries.slice(0, topK),
      summary_excerpt: note.body.slice(0, 800),
    });
  },
} as const;

// ── 7. agent.proposeFix ────────────────────────────────────────────────────
export const agentProposeFixTool = {
  name: 'agent.proposeFix',
  description:
    'Generate a READ-ONLY markdown fix proposal for a file. ' +
    'Pulls file note + cluster context + Qdrant chunks + neighbor imports — returns assembled context. ' +
    'NO writes. NO patches. Caller must review + apply manually. Use this as the gateway between vault navigation and code change.',
  parameters: z.object({
    file_path: z.string().describe('Repo-relative source file path (e.g. src/lib/server/db/client.ts)'),
    issue: z.string().describe('Brief description of the suspected issue or improvement'),
  }),
  execute: async (args: { file_path: string; issue: string }) => {
    const vaultPath = `Files/${slug(args.file_path)}.md`;
    const note = await readNote(vaultPath);
    if (!note) {
      return JSON.stringify({
        proposal_kind: 'no-vault-note',
        file_path: args.file_path,
        issue: args.issue,
        recommendation: 'Run npm run graphify:obsidian:incremental to materialize this file in the vault first.',
      });
    }

    // Pull cluster context
    let clusterCtx: Record<string, unknown> | null = null;
    if (typeof note.fm.clusterId === 'number' && note.fm.clusterId >= 0) {
      const cNote = await readNote(`Clusters/cluster-${note.fm.clusterId}.md`);
      if (cNote) {
        clusterCtx = {
          cluster_id: cNote.fm.cluster_id,
          topic: cNote.fm.topic,
          risk: cNote.fm.risk,
          top_tags: cNote.fm.top_tags ?? [],
          siblings: ((cNote.fm.contains ?? []) as string[]).slice(0, 8).map(resolveWikilink),
        };
      }
    }

    // Markdown-only proposal — never modifies any file
    const proposalMd = [
      `# Fix Proposal: \`${args.file_path}\``,
      ``,
      `**Issue:** ${args.issue}`,
      ``,
      `**Generated:** ${new Date().toISOString()} (read-only — no patches applied)`,
      ``,
      `## File context`,
      `- **PageRank:** ${note.fm.pagerank ?? 0}`,
      `- **Confidence:** ${note.fm.confidence ?? 'unknown'}`,
      `- **Cluster:** ${note.fm.clusterId ?? 'none'} (${clusterCtx?.topic ?? 'n/a'})`,
      `- **Cluster risk:** ${clusterCtx?.risk ?? 'n/a'}`,
      `- **Lines:** ${note.fm.lineCount ?? 0}`,
      `- **Tags:** ${(note.fm.tags as string[] ?? []).slice(0, 6).join(', ')}`,
      ``,
      `## Direct imports (potential change blast radius)`,
      ((note.fm.imports as string[]) ?? []).slice(0, 10).map(i => `- ${i}`).join('\n') || '_none recorded_',
      ``,
      `## Cluster siblings (related files to inspect)`,
      ((clusterCtx?.siblings as string[]) ?? []).map(s => `- ${s}`).join('\n') || '_no cluster_',
      ``,
      `## Recommended next steps`,
      `1. \`vault.read("${vaultPath}")\` — full file note`,
      `2. \`retrieval.qdrantLookup("${note.fm.embedding_id ?? `qdrant://codebase_chunks_768/${args.file_path}`}")\` — semantic chunks`,
      `3. \`vault.followLinks("${vaultPath}", "imports", 2)\` — import graph 2 hops`,
      `4. Review siblings + neighbors before drafting the change`,
      `5. Apply the change manually and re-run \`graphify:obsidian:incremental\` to refresh`,
    ].join('\n');

    return JSON.stringify({
      proposal_kind: 'read-only-markdown',
      file_path: args.file_path,
      issue: args.issue,
      vault_note: vaultPath,
      cluster: clusterCtx,
      embedding_id: note.fm.embedding_id ?? null,
      proposal_markdown: proposalMd,
    });
  },
} as const;
