// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: shared_ids.proto

package shared

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunIds carries the canonical set of IDs that travel with every pipeline run.
// Attach to any request/response that participates in a run artifact.
type RunIds struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable run UUID — identifies a single pipeline execution (k-means, SOM, ACE, etc.)
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Content-addressed chunk identity (sha256 of normalised chunk text)
	ChunkId string `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	// Cluster/community group identity — GPU k-means cluster or SOM BMU group
	GroupId string `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Symbol identity — function/class/export in the codebase AST
	SymbolId string `protobuf:"bytes,4,opt,name=symbol_id,json=symbolId,proto3" json:"symbol_id,omitempty"`
	// Stable error fingerprint (sha256 of file:line:col:code:message)
	ErrorHash string `protobuf:"bytes,5,opt,name=error_hash,json=errorHash,proto3" json:"error_hash,omitempty"`
	// Content hash — sha256 of raw source bytes for change detection
	ContentHash string `protobuf:"bytes,6,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	// Embedding model tag that produced vectors in this run
	// e.g. "embeddinggemma:latest", "nomic-embed-text"
	EmbeddingModel string `protobuf:"bytes,7,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	// Dimensionality of vectors produced in this run (e.g. 768)
	EmbeddingDim  int32 `protobuf:"varint,8,opt,name=embedding_dim,json=embeddingDim,proto3" json:"embedding_dim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunIds) Reset() {
	*x = RunIds{}
	mi := &file_shared_ids_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunIds) ProtoMessage() {}

func (x *RunIds) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ids_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunIds.ProtoReflect.Descriptor instead.
func (*RunIds) Descriptor() ([]byte, []int) {
	return file_shared_ids_proto_rawDescGZIP(), []int{0}
}

func (x *RunIds) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunIds) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *RunIds) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RunIds) GetSymbolId() string {
	if x != nil {
		return x.SymbolId
	}
	return ""
}

func (x *RunIds) GetErrorHash() string {
	if x != nil {
		return x.ErrorHash
	}
	return ""
}

func (x *RunIds) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *RunIds) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *RunIds) GetEmbeddingDim() int32 {
	if x != nil {
		return x.EmbeddingDim
	}
	return 0
}

// ArtifactRef is a pointer to a file written under memory/runs/<run_id>/
type ArtifactRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Relative path under memory/runs/<run_id>/ — e.g. "embeddings.arrow"
	RelativePath string `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	// MIME type or format hint — "application/vnd.apache.arrow.file", "application/json", etc.
	Format        string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	SizeBytes     int64  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentHash   string `protobuf:"bytes,5,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	CreatedAtUnix int64  `protobuf:"varint,6,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_shared_ids_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_shared_ids_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_shared_ids_proto_rawDescGZIP(), []int{1}
}

func (x *ArtifactRef) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ArtifactRef) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *ArtifactRef) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ArtifactRef) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactRef) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *ArtifactRef) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

var File_shared_ids_proto protoreflect.FileDescriptor

const file_shared_ids_proto_rawDesc = "" +
	"\n" +
	"\x10shared_ids.proto\x12\fyorha.shared\"\x82\x02\n" +
	"\x06RunIds\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\tR\achunkId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\tR\agroupId\x12\x1b\n" +
	"\tsymbol_id\x18\x04 \x01(\tR\bsymbolId\x12\x1d\n" +
	"\n" +
	"error_hash\x18\x05 \x01(\tR\terrorHash\x12!\n" +
	"\fcontent_hash\x18\x06 \x01(\tR\vcontentHash\x12'\n" +
	"\x0fembedding_model\x18\a \x01(\tR\x0eembeddingModel\x12#\n" +
	"\rembedding_dim\x18\b \x01(\x05R\fembeddingDim\"\xcb\x01\n" +
	"\vArtifactRef\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePath\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12!\n" +
	"\fcontent_hash\x18\x05 \x01(\tR\vcontentHash\x12&\n" +
	"\x0fcreated_at_unix\x18\x06 \x01(\x03R\rcreatedAtUnixB'Z%github.com/deeds-web-app/proto/sharedb\x06proto3"

var (
	file_shared_ids_proto_rawDescOnce sync.Once
	file_shared_ids_proto_rawDescData []byte
)

func file_shared_ids_proto_rawDescGZIP() []byte {
	file_shared_ids_proto_rawDescOnce.Do(func() {
		file_shared_ids_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_ids_proto_rawDesc), len(file_shared_ids_proto_rawDesc)))
	})
	return file_shared_ids_proto_rawDescData
}

var file_shared_ids_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_ids_proto_goTypes = []any{
	(*RunIds)(nil),      // 0: yorha.shared.RunIds
	(*ArtifactRef)(nil), // 1: yorha.shared.ArtifactRef
}
var file_shared_ids_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_ids_proto_init() }
func file_shared_ids_proto_init() {
	if File_shared_ids_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_ids_proto_rawDesc), len(file_shared_ids_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_ids_proto_goTypes,
		DependencyIndexes: file_shared_ids_proto_depIdxs,
		MessageInfos:      file_shared_ids_proto_msgTypes,
	}.Build()
	File_shared_ids_proto = out.File
	file_shared_ids_proto_goTypes = nil
	file_shared_ids_proto_depIdxs = nil
}
