import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { WikiCard, WikiGap, GapReport } from './types.js';
import { formatCardMarkdown } from './wiki-card-writer.js';

// ─────────────────────────────────────────────────────────────────────────────
// wiki-artifact-writer.ts
//
// Writes the full memory/runs/<run_id>/ artifact tree.
// Pure filesystem — no SvelteKit, no Redis, no DB.
// Called by the offline wiki:gpu-gap-analysis batch job.
//
// Output:
//   memory/runs/<run_id>/
//     wiki_gap_report.md    — human-readable gap summary
//     gap_report.json       — raw GapReport (structured)
//     wiki_cards.md         — all Karpathy-style wiki cards concatenated
//     next_actions.md       — priority-sorted patch list
//     ingest.jsonl          — ACE-ready ingestion feed (one JSON per line)
//     cluster_map.json      — placeholder (filled by GPU analysis)
//     orphan_symbols.json   — placeholder (filled by GPU analysis)
//     missing_agents_md.json — placeholder (filled by GPU analysis)
// ─────────────────────────────────────────────────────────────────────────────

export interface ArtifactWriteResult {
	runDir: string;
	filesWritten: string[];
}

// ── Main entry ───────────────────────────────────────────────────────────────

export function writeWikiArtifacts(
	report: GapReport,
	cards: WikiCard[],
	memoryRoot: string
): ArtifactWriteResult {
	const runDir = join(memoryRoot, 'runs', report.runId);
	mkdirSync(runDir, { recursive: true });

	const filesWritten: string[] = [];

	function write(name: string, content: string): void {
		const path = join(runDir, name);
		writeFileSync(path, content, 'utf-8');
		filesWritten.push(name);
	}

	write('gap_report.json', JSON.stringify(report, null, 2));
	write('wiki_gap_report.md', buildGapReportMarkdown(report));
	write('wiki_cards.md', buildAllCardsMarkdown(cards, report.gaps));
	write('next_actions.md', buildNextActionsMarkdown(report.gaps));
	write('ingest.jsonl', buildIngestJsonl(report, cards));
	write('cluster_map.json', JSON.stringify({ status: 'pending_gpu_analysis', runId: report.runId }, null, 2));
	write('orphan_symbols.json', JSON.stringify({ status: 'pending_gpu_analysis', symbols: [] }, null, 2));
	write('missing_agents_md.json', JSON.stringify({ status: 'pending_gpu_analysis', dirs: [] }, null, 2));

	return { runDir, filesWritten };
}

// ── Formatters ───────────────────────────────────────────────────────────────

function buildGapReportMarkdown(report: GapReport): string {
	const { summary, gaps, runId, generatedAt } = report;
	const open = gaps.filter((g) => g.status === 'open');
	const sorted = [...open].sort((a, b) => (b.score ?? 0) - (a.score ?? 0));

	const lines: string[] = [
		`# Wiki Gap Report — Run \`${runId}\``,
		'',
		`Generated: ${generatedAt}`,
		`Pipeline: ${report.pipelineVersion}`,
		'',
		'## Summary',
		'',
		`| Metric | Value |`,
		`|--------|-------|`,
		`| Total gaps | ${summary.total} |`,
		`| Open | ${summary.open} |`,
		`| HIGH | ${summary.high} |`,
		`| MED | ${summary.med} |`,
		`| LOW | ${summary.low} |`,
		'',
		'## Gap Scoring',
		'',
		`| Rank | ID | Title | Type | Severity | Score | Status |`,
		`|------|----|-------|------|----------|-------|--------|`,
	];

	for (let i = 0; i < sorted.length; i++) {
		const g = sorted[i];
		const type = g.type ?? '—';
		const score = g.score != null ? g.score.toFixed(2) : '—';
		lines.push(`| ${i + 1} | \`${g.id}\` | ${g.title.slice(0, 60)} | ${type} | ${g.severity} | ${score} | ${g.status} |`);
	}

	lines.push('', '## Gap Details', '');

	for (const g of sorted) {
		const icon = g.severity === 'HIGH' ? '🔴' : g.severity === 'MED' ? '🟡' : '🟢';
		lines.push(
			`### ${icon} [${g.severity}] \`${g.id}\` — ${g.title}`,
			'',
			`**Type**: ${g.type ?? 'unclassified'}  `,
			`**Score**: ${g.score?.toFixed(2) ?? '—'}`,
			'',
			`**Summary**: ${g.summary}`,
			'',
			`**Why it matters**: ${g.why}`,
			'',
			`**Patch**: ${g.patch}`,
			'',
		);
		if (g.affectedFiles.length > 0) {
			lines.push(`**Files**: ${g.affectedFiles.map((f) => `\`${f}\``).join(', ')}`, '');
		}
		if (g.affectedRedisKeys.length > 0) {
			lines.push(`**Redis keys**: ${g.affectedRedisKeys.map((k) => `\`${k}\``).join(', ')}`, '');
		}
		if (g.affectedMcpTools.length > 0) {
			lines.push(`**MCP tools**: ${g.affectedMcpTools.map((t) => `\`${t}\``).join(', ')}`, '');
		}
	}

	lines.push(`---`, `_Generated by wiki:gpu-gap-analysis · run \`${runId}\`_`);
	return lines.join('\n');
}

function buildAllCardsMarkdown(cards: WikiCard[], gaps: WikiGap[]): string {
	return cards
		.map((card) => formatCardMarkdown(card, gaps))
		.join('\n\n---\n\n');
}

function buildNextActionsMarkdown(gaps: WikiGap[]): string {
	const open = gaps
		.filter((g) => g.status === 'open')
		.sort((a, b) => (b.score ?? 0) - (a.score ?? 0));

	const lines: string[] = [
		'# Next Actions',
		'',
		'_Auto-generated from open gaps, sorted by gap score (highest impact first)._',
		'',
	];

	const sevGroups: Array<{ label: string; items: WikiGap[] }> = [
		{ label: '🔴 HIGH Priority', items: open.filter((g) => g.severity === 'HIGH') },
		{ label: '🟡 MED Priority', items: open.filter((g) => g.severity === 'MED') },
		{ label: '🟢 LOW Priority', items: open.filter((g) => g.severity === 'LOW') },
	];

	for (const group of sevGroups) {
		if (group.items.length === 0) continue;
		lines.push(`## ${group.label}`, '');
		for (const g of group.items) {
			lines.push(
				`### \`${g.id}\` — ${g.title}`,
				'',
				g.patch,
				'',
				`> Affects: ${g.affectedFiles.map((f) => `\`${f}\``).join(', ') || '(no files listed)'}`,
				'',
			);
		}
	}

	return lines.join('\n');
}

function buildIngestJsonl(report: GapReport, cards: WikiCard[]): string {
	const lines: string[] = [];

	// One record per open gap
	for (const gap of report.gaps) {
		if (gap.status !== 'open') continue;
		lines.push(JSON.stringify({
			id: `gap:${gap.id}`,
			type: 'wiki_gap',
			gapType: gap.type,
			title: gap.title,
			text: `${gap.summary}\n\nWhy: ${gap.why}\n\nPatch: ${gap.patch}`,
			severity: gap.severity,
			score: gap.score,
			files: gap.affectedFiles,
			symbols: gap.affectedSymbols,
			redisKeys: gap.affectedRedisKeys,
			mcpTools: gap.affectedMcpTools,
			runId: report.runId,
			generatedAt: report.generatedAt,
		}));
	}

	// One record per wiki card (for ACE file-path lookup)
	for (const card of cards) {
		lines.push(JSON.stringify({
			id: card.id,
			type: 'wiki_page',
			title: card.title,
			text: card.summary,
			files: card.files,
			symbols: card.symbols,
			gaps: card.gaps,
			updatedAt: card.updatedAt,
		}));
	}

	return lines.join('\n');
}
