/**
 * Source kind classification for documentation, notes, specs, and recommendations.
 * Bridges code files (AST lane) and documentation files (regex/NLP lane) into unified classifier.
 */

export type SourceKind =
  | 'code'
  | 'spec'
  | 'recommendation'
  | 'user_note'
  | 'ai_generated'
  | 'handoff'
  | 'test_log'
  | 'config'
  | 'unknown';

export const VALID_SOURCE_KINDS: readonly SourceKind[] = [
  'code',
  'spec',
  'recommendation',
  'user_note',
  'ai_generated',
  'handoff',
  'test_log',
  'config',
  'unknown'
] as const;

export function isSourceKind(value: unknown): value is SourceKind {
  return typeof value === 'string' && VALID_SOURCE_KINDS.includes(value as SourceKind);
}

/**
 * Classify packet source kind using regex + NLP heuristics.
 * Code files bypass this and use AST-grep instead.
 */
export function classifySourceKind(sourceRef: string, text: string = ''): SourceKind {
  const lower = `${sourceRef}\n${text}`.toLowerCase();

  // Code files use AST lane
  if (sourceRef.endsWith('.ts') || sourceRef.endsWith('.svelte') || sourceRef.endsWith('.go') || sourceRef.endsWith('.js')) {
    return 'code';
  }

  // Recommendation: future work, next steps, todo, blockers
  if (/\b(todo|next steps?|recommendation|risk|blocker|action item|pr review)\b/.test(lower)) {
    return 'recommendation';
  }

  // Spec: contracts, requirements, schema, acceptance criteria
  if (/\b(spec|contract|schema|requirements?|acceptance criteria|design|architecture|api)\b/.test(lower)) {
    return 'spec';
  }

  // Handoff: status summaries, session notes, completed work
  if (/\b(session|handoff|status|summary|completed|phase \d+|progress|milestone)\b/.test(lower)) {
    return 'handoff';
  }

  // User note: scratch notes, observations, manual entries
  if (/\b(user (?:said|wants|noted)|notes?|scratchpad|observation|thought|idea)\b/.test(lower)) {
    return 'user_note';
  }

  // AI generated: identified as model output, assistant response
  if (/\b(generated by|ai generated|assistant|model output|llm|gpt|claude)\b/.test(lower)) {
    return 'ai_generated';
  }

  // Test log: test results, error logs, validation output
  if (/\b(test|error log|failed|passed|validation|stderr|stdout|stack trace)\b/.test(lower)) {
    return 'test_log';
  }

  // Config: configuration files, env vars, settings
  if (/\b(config|environment|\.env|settings?|profile|options?)\b/.test(lower)) {
    return 'config';
  }

  return 'unknown';
}

/**
 * Infer feature identity (feature_id, feature_label, tree_node_id) from packet signals.
 * Used to build canonical lineage for HMM validation and RRF ranking.
 */
export function inferFeatureIdentity(input: {
  source_ref: string;
  source_kind: SourceKind;
  predicted_domain: string;
  keywords: string[];
}): {
  feature_id: string;
  feature_label: string;
  tree_node_id: string;
} {
  // Normalize path: remove prefix, strip extension
  const cleanPath = input.source_ref
    .replace(/^sveltekit-frontend\//, '')
    .replace(/^scripts\/atlas\//, '')
    .replace(/^docs\//, '')
    .replace(/\.[^.]+$/, '');

  // Top keyword as semantic signal
  const topKeyword = input.keywords.length > 0 ? input.keywords[0] : 'general';

  // feature_id: canonical identity for XGBoost + RRF
  const feature_id = `${input.predicted_domain}.${topKeyword}.${cleanPath}`.toLowerCase().replace(/[^a-z0-9_.]/g, '_');

  // feature_label: human-readable label
  const feature_label = `${input.predicted_domain} · ${topKeyword}`;

  // tree_node_id: hierarchical position in feature taxonomy
  const tree_node_id = `${input.source_kind}/${input.predicted_domain}/${topKeyword}`;

  return { feature_id, feature_label, tree_node_id };
}

/**
 * Infer HMM state: CANONICAL, RECOVERABLE, UNKNOWN.
 * Validation gate before lane routing.
 */
export function inferHmmState(f: {
  source_kind: SourceKind;
  feature_id?: string;
  tree_node_id?: string;
  domain_confidence: number;
  qdrant_point_id?: string | null;
  has_keywords: boolean;
}): 'CANONICAL' | 'RECOVERABLE' | 'UNKNOWN' {
  // Missing identity signals: unrecoverable
  if (!f.feature_id || !f.tree_node_id) return 'UNKNOWN';

  // Low confidence: recoverable (fallback to rules)
  if (f.domain_confidence < 0.35) return 'RECOVERABLE';

  // Code files without embeddings: recoverable (can extract AST)
  if (!f.qdrant_point_id && f.source_kind === 'code') return 'RECOVERABLE';

  // High confidence + keywords: canonical
  if (f.has_keywords && f.domain_confidence >= 0.7) return 'CANONICAL';

  // Default: recoverable (try fallback rules)
  return 'RECOVERABLE';
}

/**
 * Derive semantic title ID for HyperRAG lookups.
 * Used in ACE packet materialization and cached context retrieval.
 */
export function deriveSemanticTitleId(packet: {
  source_ref: string;
  feature_id?: string;
  derived_title?: string;
}): string {
  // Simple hash-like identifier combining identity signals
  const base = [
    packet.feature_id ?? 'unknown',
    packet.derived_title ?? '',
    packet.source_ref
  ]
    .join('|')
    .toLowerCase();

  // Use first 8 chars of base + last 8 chars (avoid full hash for readability)
  const prefix = base.slice(0, 8).replace(/[^a-z0-9]/g, '_');
  const suffix = base.slice(-8).replace(/[^a-z0-9]/g, '_');

  return `hyperrag:rpc:semantic_title_id:${prefix}_${suffix}`;
}
