/**
 * Mini-Active NVMe Cache reader (typed JSON snapshot of Neo4j + CouchDB).
 *
 * The hot-path companion to:
 *   - kag-cluster-source.ts (single-cluster lookups by row/col)
 *   - agents-context-source.ts (4-tier directory card lookup)
 *
 * This module loads ONE minified JSON file from disk and serves O(1) lookups
 * over four indexes:
 *   - byCluster:  "R-C" → ClusterEntry (summary + members + top tags/features)
 *   - byDirPath:  dirPath → "R-C" cluster cell
 *   - byFeature:  featureKey → ["R-C", ...] cells implementing it
 *   - byTag:      tag → ["R-C", ...] cells using it
 *
 * Backed by `mini_active_nvme_cache/agents-graph.min.json`, regenerated by
 * `npm run agents:cache` (scripts/agents/build-mini-active-cache.mjs).
 *
 * Lifecycle:
 *   - First call to any read function loads + parses the file (lazy)
 *   - Subsequent calls reuse the in-memory snapshot
 *   - `reloadMiniCache()` forces a re-read (call after the producer rebuilds)
 *   - `getMiniCacheStats()` returns metadata without forcing load
 *
 * Failure mode: if the file is missing, all readers return null/empty arrays.
 * Callers MUST treat absence as "no cluster context available" and fall through
 * to live Redis/Neo4j/CouchDB calls (see agents-context-source.ts cascade).
 */

import { readFileSync, existsSync, statSync } from 'node:fs';
import { resolve } from 'node:path';
import { z } from 'zod';

// ── Schema (must match the producer output verbatim) ─────────────────────────

export const miniCacheClusterEntrySchema = z.object({
	somRow:       z.number().int().min(0),
	somCol:       z.number().int().min(0),
	memberCount:  z.number().int().min(1),
	memberPaths:  z.array(z.string()),
	topTags:      z.array(z.string()),
	topFeatures:  z.array(z.string()),
	summary:      z.string(),
});
export type MiniCacheClusterEntry = z.infer<typeof miniCacheClusterEntrySchema>;

export const miniActiveCacheSchema = z.object({
	version:      z.string(),
	generatedAt:  z.string(),
	grid:         z.object({ rows: z.number().int().min(0), cols: z.number().int().min(0) }),
	cardCount:    z.number().int().min(0),
	clusterCount: z.number().int().min(0),
	featureCount: z.number().int().min(0),
	tagCount:     z.number().int().min(0),
	dirCount:     z.number().int().min(0),
	byCluster:    z.record(z.string(), miniCacheClusterEntrySchema),
	byDirPath:    z.record(z.string(), z.string()),       // dirPath → "R-C"
	byFeature:    z.record(z.string(), z.array(z.string())), // feature → ["R-C", ...]
	byTag:        z.record(z.string(), z.array(z.string())),
});
export type MiniActiveCache = z.infer<typeof miniActiveCacheSchema>;

// ── File resolution + lazy load ───────────────────────────────────────────────

const CACHE_FILENAME = 'agents-graph.min.json';

function cacheFilePath(): string {
	return resolve(process.cwd(), 'mini_active_nvme_cache', CACHE_FILENAME);
}

let _cache: MiniActiveCache | null = null;
let _loadedFromMtime: number | null = null;

function loadCache(): MiniActiveCache | null {
	const path = cacheFilePath();
	if (!existsSync(path)) return null;
	try {
		const stat = statSync(path);
		if (_cache && _loadedFromMtime === stat.mtimeMs) return _cache;
		const raw = JSON.parse(readFileSync(path, 'utf-8'));
		_cache = miniActiveCacheSchema.parse(raw);
		_loadedFromMtime = stat.mtimeMs;
		return _cache;
	} catch {
		return null;
	}
}

/** Force a re-read on next call (after the producer rebuilds the file). */
export function reloadMiniCache(): void {
	_cache = null;
	_loadedFromMtime = null;
}

/** Metadata-only — does not force load if file is missing. */
export function getMiniCacheStats(): {
	present: boolean;
	mtimeMs: number | null;
	bytes:   number | null;
	loaded:  boolean;
} {
	const path = cacheFilePath();
	if (!existsSync(path)) {
		return { present: false, mtimeMs: null, bytes: null, loaded: _cache !== null };
	}
	const stat = statSync(path);
	return { present: true, mtimeMs: stat.mtimeMs, bytes: stat.size, loaded: _cache !== null };
}

// ── O(1) lookups ──────────────────────────────────────────────────────────────

/** Get the cluster entry for a SOM cell. Null if cell not populated or cache missing. */
export function getClusterByCell(row: number, col: number): MiniCacheClusterEntry | null {
	const cache = loadCache();
	if (!cache) return null;
	return cache.byCluster[`${row}-${col}`] ?? null;
}

/** Get the SOM cell ("R-C") for a directory path. Null if dir not in any cluster. */
export function getCellForDirPath(dirPath: string): string | null {
	const cache = loadCache();
	if (!cache) return null;
	return cache.byDirPath[dirPath] ?? null;
}

/** Get all cluster cells implementing a feature. Empty array on miss. */
export function getCellsForFeature(featureKey: string): string[] {
	const cache = loadCache();
	if (!cache) return [];
	return cache.byFeature[featureKey] ?? [];
}

/** Get all cluster cells using a tag. Empty array on miss. */
export function getCellsForTag(tag: string): string[] {
	const cache = loadCache();
	if (!cache) return [];
	return cache.byTag[tag] ?? [];
}

/** Walk a file path up its directory tree, return the first cell hit. */
export function getCellForFilePath(filePath: string): string | null {
	const cache = loadCache();
	if (!cache) return null;
	const segments = filePath.replace(/\\/g, '/').split('/').filter(Boolean);
	if (segments.length > 0 && segments[segments.length - 1].includes('.')) segments.pop();
	for (let i = segments.length; i > 0; i--) {
		const dir = segments.slice(0, i).join('/');
		const cell = cache.byDirPath[dir];
		if (cell) return cell;
	}
	return null;
}

/**
 * High-level: query string → ranked cluster cells via tag overlap.
 * Pure in-memory — no Redis/Neo4j round trip.
 */
export interface MiniCachePick {
	cell:    string;
	score:   number;
	overlap: string[];
}

export function pickCellsForKeywords(keywords: readonly string[], topN = 3): MiniCachePick[] {
	const cache = loadCache();
	if (!cache || keywords.length === 0) return [];

	const cellHits = new Map<string, Set<string>>();
	for (const kw of keywords) {
		const lc = kw.toLowerCase();
		const cells = cache.byTag[lc] ?? cache.byTag[kw] ?? [];
		for (const cell of cells) {
			let s = cellHits.get(cell);
			if (!s) { s = new Set(); cellHits.set(cell, s); }
			s.add(lc);
		}
	}

	const picks: MiniCachePick[] = [];
	for (const [cell, hits] of cellHits) {
		picks.push({
			cell,
			score: hits.size / Math.max(keywords.length, 1),
			overlap: [...hits],
		});
	}
	picks.sort((a, b) => b.score - a.score);
	return picks.slice(0, topN);
}
