import { describe, expect, it } from 'vitest';
import { CanonicalAcePacketEnvelopeSchema } from '$lib/server/ace/canonical-packet-envelope.js';
import { FeatureMatrixRowV1Schema } from '$lib/server/atlas/feature-matrix-schema.js';
import { createValidationResultV1 } from './validation-result-v1.js';
import {
  buildClassificationEnvelopeV1,
  validateClassificationLineage,
} from './classification-envelope-v1.js';

describe('Classification envelope alignment', () => {
  it('keeps packet, feature row, validation, and ledger identity aligned', () => {
    const now = '2026-07-28T00:00:00.000Z';

    const packet = CanonicalAcePacketEnvelopeSchema.parse({
      packet_key: 'pkt_0123456789abcdef0123456789abcdef',
      source_ref: 'src/lib/server/auth.ts',
      canonical_source_ref: 'src/lib/server/auth.ts',
      title_id: 'title:auth',
      feature_id: 'auth.sessions',
      feature_label: 'Authentication Sessions',
      domain_class: 'infrastructure',
      lane_status: 'ACTIVE',
      evidence_state: 'ACTIVE_VERIFIED',
      knowledge_resolution: 'RESOLVED',
      ontology_ids: ['ontology:auth'],
      concept_ids: ['concept:session'],
      runtime_evidence_refs: ['runtime:trace:1'],
      test_evidence_refs: ['test:spec:1'],
      used_concepts: ['session'],
      lexical_nouns: ['session'],
      lexical_verbs: ['validate'],
      lexical_adverbs_ly: [],
      relationship_hints: [],
      routing_hints: [],
      adjacency_packet_keys: [],
      adjacency_feature_ids: [],
      adjacency_source_refs: [],
      packed_arrays: {
        packet_keys: [],
        feature_ids: [],
        source_refs: [],
        title_ids: [],
      },
      columnar_tables: [],
      mmap_vector_refs: [],
      language: 'typescript',
      kind: 'function',
      page_rank_score: 0.84,
      prompt_template_id: 'prompt:classification',
      summary: 'Validate auth sessions.',
      created_at: now,
    });

    const featureRow = FeatureMatrixRowV1Schema.parse({
      schema_version: '1.0',
      created_at: now,
      updated_at: now,
      workspace_revision: 'main',
      lane_status: 'ACTIVE',
      evidence_state: 'ACTIVE_VERIFIED',
      knowledge_resolution: 'RESOLVED',
      identity: {
        packet_key: packet.packet_key,
        source_ref: packet.source_ref,
        file_path: 'src/lib/server/auth.ts',
        function_symbol: 'validateSession',
        feature_id: packet.feature_id ?? 'auth.sessions',
        title_id: packet.title_id ?? 'title:auth',
        tree_node_id: packet.tree_node_id ?? 'tree:src/lib/server/auth.ts:validateSession',
      },
      dense_768: null,
      dense_384: null,
      latent_64: null,
      lexical: null,
      topology: null,
      classifiers: null,
      is_valid: true,
      validation_errors: [],
      feature_labels: ['auth', 'sessions'],
      domain_class: 'infrastructure',
      secondary_domains: ['platform', 'identity'],
      ontology_ids: ['ontology:auth'],
      concept_ids: ['concept:session'],
      runtime_evidence_refs: ['runtime:trace:1'],
      test_evidence_refs: ['test:spec:1'],
    });

    const validation = createValidationResultV1({
      packetKey: packet.packet_key,
      workspaceId: 'workspace:main',
      validatedBy: 'phase-108d-proof-matrix',
      phase: '108d-proof-matrix',
      projections: {
        postgres: {
          layer: 'POSTGRES',
          packetKey: packet.packet_key,
          sourceRef: packet.source_ref,
          featureId: packet.feature_id ?? null,
          treeNodeId: featureRow.identity.tree_node_id ?? null,
          workspaceId: 'workspace:main',
          contentHash: 'sha256:content',
          workspaceRevision: 'main',
          ontologyVersion: 'ontology:v1',
          laneStatus: 'ACTIVE',
          evidenceState: 'ACTIVE_VERIFIED',
          knowledgeResolution: 'RESOLVED',
          domainClass: 'infrastructure',
          featureLabel: 'Authentication Sessions',
          snapshotAt: new Date(now),
        },
        qdrant: {
          layer: 'QDRANT',
          packetKey: packet.packet_key,
          sourceRef: packet.source_ref,
          featureId: packet.feature_id ?? null,
          treeNodeId: featureRow.identity.tree_node_id ?? null,
          workspaceId: 'workspace:main',
          contentHash: 'sha256:content',
          workspaceRevision: 'main',
          ontologyVersion: 'ontology:v1',
          laneStatus: 'ACTIVE',
          evidenceState: 'ACTIVE_VERIFIED',
          knowledgeResolution: 'RESOLVED',
          domainClass: 'infrastructure',
          featureLabel: 'Authentication Sessions',
          snapshotAt: new Date(now),
        },
        redis: {
          layer: 'REDIS',
          packetKey: packet.packet_key,
          sourceRef: packet.source_ref,
          featureId: packet.feature_id ?? null,
          treeNodeId: featureRow.identity.tree_node_id ?? null,
          workspaceId: 'workspace:main',
          contentHash: 'sha256:content',
          workspaceRevision: 'main',
          ontologyVersion: 'ontology:v1',
          laneStatus: 'ACTIVE',
          evidenceState: 'ACTIVE_VERIFIED',
          knowledgeResolution: 'RESOLVED',
          domainClass: 'infrastructure',
          featureLabel: 'Authentication Sessions',
          snapshotAt: new Date(now),
        },
        hyperrag_rpc: {
          layer: 'HYPERRAG_RPC',
          packetKey: packet.packet_key,
          sourceRef: packet.source_ref,
          featureId: packet.feature_id ?? null,
          treeNodeId: featureRow.identity.tree_node_id ?? null,
          workspaceId: 'workspace:main',
          contentHash: 'sha256:content',
          workspaceRevision: 'main',
          ontologyVersion: 'ontology:v1',
          laneStatus: 'ACTIVE',
          evidenceState: 'ACTIVE_VERIFIED',
          knowledgeResolution: 'RESOLVED',
          domainClass: 'infrastructure',
          featureLabel: 'Authentication Sessions',
          snapshotAt: new Date(now),
        },
        ace: {
          layer: 'ACE',
          packetKey: packet.packet_key,
          sourceRef: packet.source_ref,
          featureId: packet.feature_id ?? null,
          treeNodeId: featureRow.identity.tree_node_id ?? null,
          workspaceId: 'workspace:main',
          contentHash: 'sha256:content',
          workspaceRevision: 'main',
          ontologyVersion: 'ontology:v1',
          laneStatus: 'ACTIVE',
          evidenceState: 'ACTIVE_VERIFIED',
          knowledgeResolution: 'RESOLVED',
          domainClass: 'infrastructure',
          featureLabel: 'Authentication Sessions',
          snapshotAt: new Date(now),
        },
      },
      violations: [],
    });

    const classification = buildClassificationEnvelopeV1({
      identity: {
        packetKey: packet.packet_key,
        sourceRef: packet.source_ref,
        contentHash: 'sha256:content',
        workspaceRevision: 'main',
        featureId: packet.feature_id ?? 'auth.sessions',
        featureLabel: packet.feature_label ?? 'Authentication Sessions',
        titleId: packet.title_id ?? null,
        treeNodeId: featureRow.identity.tree_node_id ?? null,
        qdrantPointId: packet.qdrant_point_id ?? null,
      },
      signals: {
        laneStatus: 'ACTIVE',
        evidenceState: 'ACTIVE_VERIFIED',
        knowledgeResolution: 'RESOLVED',
        domainClass: 'infrastructure',
        secondaryDomains: ['platform', 'identity'],
        ontologyIds: ['ontology:auth'],
        conceptIds: ['concept:session'],
        runtimeEvidenceRefs: ['runtime:trace:1'],
        testEvidenceRefs: ['test:spec:1'],
        partOfSpeech: 'NOUN',
        pageRankScore: packet.page_rank_score,
        communityId: packet.community_id ?? null,
        kmeansCluster: packet.kmeans_cluster ?? null,
        somCell: packet.som_cell ?? null,
        somRow: packet.som_row ?? null,
        somCol: packet.som_col ?? null,
        classifiers: {
          naiveBayesClass: 'auth.sessions',
          naiveBayesScore: 0.91,
          logisticRegressionScore: 0.88,
          xgboostScore: 0.93,
          computedAt: now,
        },
      },
      representations: {
        semantic_768: {
          name: 'semantic_768',
          role: 'SEMANTIC_AUTHORITY',
          laneStatus: 'ACTIVE',
          producerVersion: 'embeddinggemma:768:v1',
          modelId: 'embeddinggemma',
          dimension: 768,
          projectionVersion: null,
          normalized: true,
        },
        semantic768: {
          name: 'semantic_768',
          role: 'SEMANTIC_AUTHORITY',
          laneStatus: 'ACTIVE',
          producerVersion: 'embeddinggemma:768:v1',
          modelId: 'embeddinggemma',
          dimension: 768,
          projectionVersion: null,
          normalized: true,
        },
        dense768: {
          name: 'dense_768',
          role: 'SEMANTIC_AUTHORITY',
          laneStatus: 'ACTIVE',
          producerVersion: 'embeddinggemma:768:v1',
          modelId: 'embeddinggemma',
          dimension: 768,
          projectionVersion: null,
          normalized: true,
        },
        dense384: {
          name: 'dense_384',
          role: 'ONLINE_RETRIEVAL',
          laneStatus: 'ACTIVE',
          producerVersion: 'embeddinggemma:384:v1',
          modelId: 'embeddinggemma',
          dimension: 384,
          projectionVersion: 'projection:v1',
          normalized: true,
        },
        latent64: {
          name: 'latent_64',
          role: 'ROUTING',
          laneStatus: 'MIGRATION_SOURCE',
          producerVersion: 'ae:64:v1',
          modelId: 'autoencoder',
          dimension: 64,
          projectionVersion: 'routing:v1',
          normalized: false,
        },
      },
      validation: {
        layer: 'validation',
        packetKey: packet.packet_key,
        sourceRef: packet.source_ref,
        contentHash: 'sha256:content',
        workspaceRevision: 'main',
        validatedBy: 'phase-108d-proof-matrix',
        phase: '108d-proof-matrix',
        canPromotion: validation.canPromotion,
        isValid: validation.isValid,
        outcome: 'success',
        ledgerPath: '.opencode/outcome-ledger.ndjson',
        recordedAt: now,
      },
      provenance: {
        packetSchemaVersion: 'atlas.canonical-ace-packet-envelope-v1',
        featureSchemaVersion: '1.0',
        validationSchemaVersion: '1.0',
        ledgerSchemaVersion: 'outcome-ledger.ndjson',
        serializerVersion: 'unit-test',
        createdAt: now,
      },
    });

    const lineage = validateClassificationLineage({
      identity: classification.identity,
      featureRow: {
        identity: featureRow.identity,
        lane_status: featureRow.lane_status,
        evidence_state: featureRow.evidence_state,
        knowledge_resolution: featureRow.knowledge_resolution,
      },
      validation: classification.validation,
      ledger: {
        packetKey: packet.packet_key,
        sourceRef: packet.source_ref,
        contentHash: 'sha256:content',
        workspaceRevision: 'main',
        laneStatus: 'ACTIVE',
        evidenceState: 'ACTIVE_VERIFIED',
        knowledgeResolution: 'RESOLVED',
      },
    });

    expect(classification.identity.packetKey).toBe(featureRow.identity.packet_key);
    expect(classification.identity.sourceRef).toBe(packet.source_ref);
    expect(validation.canPromotion).toBe('CROSS_STORE_PROVEN');
    expect(lineage.aligned).toBe(true);
    expect(lineage.violations).toHaveLength(0);
    expect(classification.signals.secondaryDomains).toEqual(['platform', 'identity']);
    expect(classification.signals.partOfSpeech).toBe('NOUN');
  });

  it('flags a packet key drift as a hard gap', () => {
    const lineage = validateClassificationLineage({
      identity: {
        packetKey: 'pkt_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
        sourceRef: 'src/lib/server/auth.ts',
        contentHash: 'sha256:content',
        workspaceRevision: 'main',
        featureId: 'auth.sessions',
        featureLabel: 'Authentication Sessions',
      },
      validation: {
        layer: 'validation',
        packetKey: 'pkt_bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
        sourceRef: 'src/lib/server/auth.ts',
        contentHash: 'sha256:content',
        workspaceRevision: 'main',
      },
    });

    expect(lineage.aligned).toBe(false);
    expect(lineage.violations.some((violation) => violation.code === 'PACKET_KEY_MISMATCH')).toBe(true);
  });
});
