/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Hash each source_ref string with XxHash64 (seed 42).
 * Returns a Buffer of raw little-endian u64 bytes (8 bytes per hash).
 *
 * JS side:
 *   const buf = hashSourceRefs(refs)
 *   const ids = new BigUint64Array(buf.buffer, buf.byteOffset, buf.length / 8)
 */
export declare function hashSourceRefs(refs: Array<string>): Buffer
/**
 * Remove duplicate directed edges (same src+dst+type).
 * Input/output: JSON string of EdgePacket[].
 */
export declare function dedupeEdgesJson(edgesJson: string): string
/**
 * Score SOM candidate cells against a query cell using Euclidean distance
 * on a 20×20 grid. Returns Float32Array of scores in (0, 1].
 * 1.0 = same cell. Cell index = row * 20 + col. Uint16 range 0–399.
 */
export declare function scoreSom20X20(queryCell: number, candidateCells: Array<number>): Float32Array
/**
 * Read a JSONL file and return the rows as a JSON string.
 * Uses Rayon parallel parse; falls back to serde_json per line.
 */
export declare function loadJsonlPackets(path: string): string
/**
 * Read atlas nodes JSONL + edges JSONL, join on source_ref, assemble
 * QdrantPayload structs with lane_ids, feature_ids, SOM coords, and
 * return as MessagePack Buffer ready for direct Qdrant upsert.
 *
 * Pure data transformer — never touches Qdrant or any network socket.
 */
export declare function packQdrantPayloads(nodesPath: string, edgesPath: string): Buffer
/**
 * Verify the turbovec quantization crate is linked and functional.
 * Builds a TurboQuantIndex with dim float32 vectors at `bits` precision.
 */
export declare function turbovecSmoke(dim: number, bits: number): string
/**
 * Exact cosine top-k (oracle). `vectors` is n*dim, `queries` is nq*dim, row-major. Rows are L2-normalised
 * here so callers may pass unnormalised data. Returns nq*k row indices then nq*k scores (as two arrays).
 */
export interface TopKResult {
  indices: Array<number>
  scores: Array<number>
}
export declare function hintExactCosineTopk(vectors: Float32Array, queries: Float32Array, dim: number, k: number): TopKResult
/** Quantized turbovec top-k (challenger). Same layout and return shape as the exact oracle. */
export declare function hintTurbovecTopk(vectors: Float32Array, queries: Float32Array, dim: number, bits: number, k: number): TopKResult
