/**
 * wrapper.d.ts — stable public type declarations for crates/turbovec-napi
 *
 * Import from wrapper.js, not index.js (index.js is auto-generated by napi-rs
 * on every build; wrapper.js survives rebuilds and fixes BigUint64Array typing).
 */

export interface AtlasNode {
  card_id: string
  source_ref?: string
  som_row?: number
  som_col?: number
  som_dist?: number
  tags?: string[]
  keywords?: string[]
  feature_ids?: string[]
  lane_ids?: string[]
  summary?: string
  kind?: string
  area?: string
}

export interface EdgePacket {
  src: string
  dst: string
  type?: string
  feature_ids?: string[]
  lane_ids?: string[]
  confidence?: number
}

export interface QdrantPayload {
  source_ref: string
  som_cell?: string
  som_row?: number
  som_col?: number
  feature_id?: string
  feature_ids: string[]
  lane_ids: string[]
  tags: string[]
  keywords: string[]
  kind?: string
  area?: string
  summary?: string
}

/**
 * Hash each sourceRef string with XxHash64 (seed 42).
 * Returns BigUint64Array — use as Valkey packet keys and Qdrant point IDs.
 * (wrapper.js converts the native Buffer → BigUint64Array zero-copy)
 */
export declare function hashSourceRefs(refs: string[]): BigUint64Array

/**
 * Remove duplicate directed edges (same src+dst+type).
 * Input/output: JSON string of EdgePacket[]. Preserves first occurrence.
 */
export declare function dedupeEdgesJson(edgesJson: string): string

/**
 * Score SOM candidate cells against a query cell using Euclidean distance
 * on a 20×20 grid. Returns Float32Array scores in (0, 1].
 * Cell index = row * 20 + col. Valid range: uint16 0–399.
 */
export declare function scoreSom20X20(queryCell: number, candidateCells: number[]): Float32Array

/**
 * Read a JSONL file and return rows as a JSON string.
 * SIMD JSON (Rayon parallel) with serde_json per-line fallback.
 */
export declare function loadJsonlPackets(path: string): string

/**
 * Read atlas nodes JSONL + edges JSONL, join on source_ref, assemble
 * QdrantPayload structs (lane_ids, feature_ids, SOM coords) and return
 * MessagePack Buffer ready for Qdrant upsert.
 * Pure data transformer — never opens a network socket.
 */
export declare function packQdrantPayloads(nodesPath: string, edgesPath: string): Buffer

/**
 * Verify the turbovec TurboQuantIndex is linked and functional.
 */
export declare function turbovecSmoke(dim: number, bits: number): string
