'use strict'
// Stable public API for crates/turbovec-napi.
// index.js is auto-generated by napi-rs on every build — import from here instead.
const native = require('./index.js')

// hashSourceRefs: native returns Buffer of raw LE u64 bytes.
// Wrap as BigUint64Array for zero-copy typed access.
function hashSourceRefs(refs) {
  const buf = native.hashSourceRefs(refs)
  return new BigUint64Array(buf.buffer, buf.byteOffset, buf.length / 8)
}

module.exports = {
  hashSourceRefs,
  dedupeEdgesJson: native.dedupeEdgesJson,
  scoreSom20X20: native.scoreSom20X20,
  loadJsonlPackets: native.loadJsonlPackets,
  packQdrantPayloads: native.packQdrantPayloads,
  turbovecSmoke: native.turbovecSmoke,
}
