/**
 * Canonical analytics event envelope.
 *
 * Every domain — retrieval, recommendation, ACP, dispatcher, lane telemetry,
 * user interaction — emits this single shape. The envelope is stored in
 * Postgres analytics_events(payload jsonb) and fanned out via Redis Streams
 * (analytics:events, MAXLEN ~50 000).
 *
 * Design rules:
 *   - Callers must NOT await emit(); it is fire-and-forget.
 *   - Postgres is the durable ledger; Redis Streams is the live fanout.
 *   - Never carry raw user PII — use pseudonymized actor_key or userId int.
 *   - traceId propagates across the full request so lanes can be correlated.
 */

import { z } from 'zod';

// ---------------------------------------------------------------------------
// Event type registry
// ---------------------------------------------------------------------------

export const AnalyticsEventTypeSchema = z.enum([
  // Request lifecycle
  'request.received',
  'request.routed',
  // Lane results (one event per lane per request)
  'lane.result',
  // Candidate selection
  'candidate.selected',
  // Topology context
  'centroid.assigned',
  'som.cell.assigned',
  // Recommendation lifecycle
  'recommendation.impression',
  'recommendation.click',
  'recommendation.accept',
  'recommendation.dismiss',
  // ACP packet lifecycle
  'acp.packet.created',
  'acp.packet.promoted',
  // Cache signals
  'cache.hit',
  'cache.miss',
  // Errors (non-fatal, for analytics — not exceptions)
  'error.occurred',
]);

export type AnalyticsEventType = z.infer<typeof AnalyticsEventTypeSchema>;

// ---------------------------------------------------------------------------
// Core envelope
// ---------------------------------------------------------------------------

export const AnalyticsEventSchema = z.object({
  /** UUID generated by the emitter; used for dedup on replay. */
  eventId: z.string().uuid(),

  /** ISO-8601 wall clock at emit time. */
  occurredAt: z.string().datetime(),

  /** Discriminator. */
  eventType: AnalyticsEventTypeSchema,

  // ── Correlation ──────────────────────────────────────────────────────────

  /**
   * Propagated from the HTTP request or ACP workflow.
   * Ties all lane.result / candidate.selected / centroid.assigned events
   * for a single query into one traceable unit.
   */
  traceId: z.string().min(1),

  /** Browser or agent session — pseudonymized or opaque. */
  sessionId: z.string().optional(),

  /**
   * Integer Postgres user id (locals.user.id).
   * Omit for anonymous or ACP-only events.
   */
  userId: z.number().int().positive().optional(),

  // ── Request identity ─────────────────────────────────────────────────────

  /** SHA-256(query_text)[:16] — stable hash, not raw text. */
  queryHash: z.string().optional(),

  // ── Packet / chunk identity ───────────────────────────────────────────────

  /** atlas_packets.packet_key */
  packetKey: z.string().optional(),

  /** atlas_packets.source_ref */
  sourceRef: z.string().optional(),

  // ── Lane / retrieval context ──────────────────────────────────────────────

  /**
   * Which retrieval lane produced this event.
   * Mirrors RetrievalSearchLane from search-contract.ts.
   */
  laneId: z.string().optional(),

  /** RRF or per-lane score at the time of this event. */
  score: z.number().optional(),

  /** Rank position in the result list (1-based). */
  rank: z.number().int().positive().optional(),

  // ── Topology context ──────────────────────────────────────────────────────

  /** K-means or SOM cluster centroid id. */
  centroidId: z.string().optional(),

  /** Flattened SOM cell index (row * 20 + col, 0-399). */
  somCell: z.number().int().min(0).max(399).optional(),

  /** Karpathy authority blend score [0, 1]. */
  authorityScore: z.number().min(0).max(1).optional(),

  /** Raw Neo4j PageRank (L1-normalised). */
  pagerankRaw: z.number().min(0).optional(),

  // ── Timing ───────────────────────────────────────────────────────────────

  /** Wall-clock duration for the operation this event describes (ms). */
  latencyMs: z.number().nonnegative().optional(),

  // ── Open payload ─────────────────────────────────────────────────────────

  /**
   * Domain-specific extra fields that don't belong in the fixed schema.
   * Keep shallow — deeply nested payloads defeat SQL JSONB indexing.
   */
  metadata: z.record(z.string(), z.unknown()).optional(),
});

export type AnalyticsEventEnvelope = z.infer<typeof AnalyticsEventSchema>;

