#!/usr/bin/env tsx
import fs from 'node:fs/promises'; import path from 'node:path'; import {createHash} from 'node:crypto';
import {createAtlasDuckDB,parsePgVector} from '../../../packages/atlas-duckdb/src/index.ts';
import {candidateOrdinalMapV1Schema} from '../../src/lib/server/atlas/features/canonical-candidate-v1.js';
import {candidateFeatureColumnarV1Schema} from '../../src/lib/server/atlas/features/candidate-feature-columnar-v1.js';
import {CandidateOrdinalSetV1Schema} from '../../src/lib/server/atlas/kernel/candidate-ordinal-set-v1.js';
import {adaptCandidateFeatureColumnarToSampleQueryMatrixV1,adaptExactCandidateOrdinalSetToSamplingTargetSetV1,adaptSemanticRowsToRowL2SampleQueryMatrixV1} from '../../src/lib/server/atlas/sampling/sample-query-artifact-adapters-v1.js';
import {compareSamplingMatricesV1} from '../../src/lib/server/atlas/sampling/sample-query-corpus-evaluation-v1.js';
function arg(n:string,f?:string){const p=`--${n}=`;const v=process.argv.slice(2).find(x=>x.startsWith(p));if(v)return v.slice(p.length);const i=process.argv.indexOf(`--${n}`);return i>=0?process.argv[i+1]:f;} function req(n:string){const v=arg(n)?.trim();if(!v)throw new Error(`SAMPLE_QUERY_CORPUS_ARGUMENT_REQUIRED:${n}`);return v;}
function esc(v:string){return v.replaceAll("'","''");} async function json(p:string){return JSON.parse(await fs.readFile(p,'utf8'));} async function hashFile(p:string){return createHash('sha256').update(await fs.readFile(p)).digest('hex');}
function seeds(raw:string|undefined){const s=(raw??'1,7,42,99,2026,65537,104729').split(',').map(v=>Number.parseInt(v.trim(),10));if(!s.length||s.some(v=>!Number.isInteger(v)||v<0||v>0xffffffff)||new Set(s).size!==s.length)throw new Error('SAMPLE_QUERY_CORPUS_SEEDS_INVALID');return s;}
async function semanticRows(p:string){const db=await createAtlasDuckDB({databasePath:':memory:'});try{const rows=await db.connection.query(`SELECT packet_key, semantic_embedding_768 FROM read_parquet('${esc(path.resolve(p))}') ORDER BY packet_key`);if(!rows.length)throw new Error('SAMPLE_QUERY_SEMANTIC_PARQUET_EMPTY');return rows.map(r=>({packetKey:String(r.packet_key??'').trim(),values:parsePgVector(r.semantic_embedding_768)}));}finally{await db.close();}}
async function main(){
 const ordinalPath=path.resolve(req('ordinal-map')), semanticPath=path.resolve(req('semantic-parquet')), featurePath=path.resolve(req('feature-columnar')), exactPath=path.resolve(req('exact-candidate-set')), output=path.resolve(req('output'));
 const sampleSize=Number.parseInt(arg('sample-size','64')!,10), targetK=Number.parseInt(arg('target-k','10')!,10), seedList=seeds(arg('seeds')), producerRevision=arg('producer-revision','sample-query-corpus-evaluator:v1')!;
 const ordinalMap=candidateOrdinalMapV1Schema.parse(await json(ordinalPath)); const columnar=candidateFeatureColumnarV1Schema.parse(await json(featurePath)); const exact=CandidateOrdinalSetV1Schema.parse(await json(exactPath)); const rows=await semanticRows(semanticPath); const semanticArtifactChecksum=await hashFile(semanticPath);
 const semanticMatrix=adaptSemanticRowsToRowL2SampleQueryMatrixV1({ordinalMap,semanticRows:rows,expectedDimension:768,sourceMatrixRevision:exact.representationRevision,sourceArtifactChecksum:semanticArtifactChecksum,producerRevision});
 const featureMatrix=adaptCandidateFeatureColumnarToSampleQueryMatrixV1({ordinalMap,columnar,mode:'COLUMN_STANDARDIZED_WITH_PRESENCE',producerRevision});
 const targetSet=adaptExactCandidateOrdinalSetToSamplingTargetSetV1({candidateSet:exact,topK:targetK,producerRevision});
 const comparison=compareSamplingMatricesV1({left:semanticMatrix,right:featureMatrix,targetSet,sampleSize,seeds:seedList,producerRevision});
 const receipt={schema:'atlas.sample-query-real-corpus-proof.v1',status:'SAMPLE_QUERY_REAL_CORPUS_MEASURED_NOT_PROMOTED',inputs:{ordinalMapPath:ordinalPath,semanticParquetPath:semanticPath,semanticArtifactChecksum,featureColumnarPath:featurePath,exactCandidateSetPath:exactPath,candidateSnapshotRevision:ordinalMap.candidateSnapshotRevision,ordinalMapChecksum:ordinalMap.ordinalMapChecksum,rowCount:ordinalMap.rowCount,targetK,sampleSize,seeds:seedList},semantic:{matrixChecksum:semanticMatrix.matrixChecksum,rowNormCoefficientOfVariation:semanticMatrix.rowNormCoefficientOfVariation,lengthSquaredDegeneratesTowardUniform:semanticMatrix.lengthSquaredDegeneratesTowardUniform,columnCount:semanticMatrix.columnCount},feature:{matrixChecksum:featureMatrix.matrixChecksum,rowNormCoefficientOfVariation:featureMatrix.rowNormCoefficientOfVariation,lengthSquaredDegeneratesTowardUniform:featureMatrix.lengthSquaredDegeneratesTowardUniform,columnCount:featureMatrix.columnCount,featureProjection:'COLUMN_STANDARDIZED_WITH_PRESENCE'},comparison,interpretation:{lengthSquaredBeatsUniformOnFeatureMatrix:comparison.right.lengthSquaredDeltaVsUniformMean>0,lowRankPromotionAuthorized:false,rtxAccelerationAuthorized:false,retrievalVoteProduced:false},canonicalWritesAttempted:false,postgresAccessed:false,qdrantAccessed:false,neo4jAccessed:false,valkeyAccessed:false};
 await fs.mkdir(path.dirname(output),{recursive:true});await fs.writeFile(output,`${JSON.stringify(receipt,null,2)}\n`,'utf8');console.log(JSON.stringify(receipt,null,2));
}
main().catch(e=>{console.error(e instanceof Error?e.stack??e.message:String(e));process.exitCode=1;});
