import { QdrantManager } from '../vector/qdrant-manager.js';
import { getNeo4jDriver } from '../neo4j-driver.js';
import { couchPut } from './karpathy-wiki.js';
import type { KarpathyHookOutput } from './karpathy-hook.js';
import db from '$lib/server/db/client.js';
import { topologySnapshots, topologyPositions } from '$lib/server/db/schema.js';

/**
 * Karpathy Persistence: Commits the organized artifacts from Karpathy Hook
 * to the various durable backends (Qdrant, Neo4j, Postgres, CouchDB).
 */
export async function persistKarpathyHook(output: KarpathyHookOutput) {
	const qdrant = new QdrantManager();
	const neo4j = getNeo4jDriver();

	// 1. Qdrant: Vector Payloads (Chunks)
	if (output.qdrantPayloads.length > 0) {
		// We'll assume embeddings are already generated or will be generated by the caller
		// For the indexer script, we'll likely generate them before calling persist.
	}

	// 2. Neo4j: Graph Topology
	if (output.neo4jEdges.length > 0) {
		const session = neo4j.session({ database: 'neo4j' });
		try {
			for (const edge of output.neo4jEdges) {
				await session.run(`
					MERGE (s {id: $source})
					MERGE (t {id: $target})
					MERGE (s)-[:${edge.type}]->(t)
				`, { source: edge.source, target: edge.target });
			}
		} catch (error) {
			console.error('[persistence] Neo4j edge sync failed:', error);
		} finally {
			await session.close();
		}
	}

	// 3. CouchDB/Redis: Wiki Notes
	for (const note of output.wikiNotes) {
		try {
			await couchPut(note);
		} catch (error) {
			console.error(`[persistence] WikiNote sync failed for ${note.type}:`, error);
		}
	}

	// 4. Postgres: Topology Snapshots (Audit)
	if (output.libtorchRows.length > 0) {
		try {
			const [snap] = await db.insert(topologySnapshots).values({
				runId: output.runId,
				repoRoot: '',
				metadata: { filesSeen: output.stats.filesSeen, chunksCreated: output.stats.chunksCreated },
			}).returning({ id: topologySnapshots.id });

			if (snap) {
				for (const row of output.libtorchRows) {
					await db.insert(topologyPositions).values({
						snapshotId: snap.id,
						stableKey: row.stableKey,
						x: 0,
						y: 0,
						z: 0,
						t: 0,
						metadata: { filePath: row.filePath, tags: row.tags },
					}).onConflictDoUpdate({
						target: [topologyPositions.snapshotId, topologyPositions.stableKey],
						set: { metadata: { filePath: row.filePath, tags: row.tags } },
					});
				}
			}
		} catch (error) {
			console.error('[persistence] Postgres topology sync failed:', error);
		}
	}

	console.log(`[persistence] Run ${output.runId} persisted successfully.`);
	return { success: true, stats: output.stats };
}
