import { z } from 'zod';

export const EncoderTrainingManifestV1Schema = z.object({
  schemaVersion: z.literal('atlas.encoder-training-manifest.v1'),
  encoderId: z.string().min(1),
  task: z.enum(['intent_domain_classifier', 'tool_cross_encoder']),
  baseModel: z.string().min(1),
  adaptation: z.enum(['full_finetune', 'lora', 'adalora', 'qlora']),
  trainSplitRevision: z.string().min(1),
  validationSplitRevision: z.string().min(1),
  featureContractRevision: z.string().min(1),
  toolRegistryRevision: z.string().min(1),
  maxSequenceLength: z.number().int().positive(),
  batchSize: z.number().int().positive(),
  gradientAccumulationSteps: z.number().int().positive(),
  precision: z.enum(['fp32', 'fp16', 'bf16']),
  targetModules: z.array(z.string()).default([]),
  rankBudget: z.number().int().nonnegative().nullable(),
  quantization: z.enum(['none', 'int8', 'nf4']).default('none'),
  metrics: z.array(z.enum([
    'tool_recall_at_1',
    'tool_recall_at_3',
    'tool_recall_at_5',
    'mrr',
    'ndcg_at_5',
    'execution_success_at_k',
    'ece',
    'brier',
  ])).min(1),
  promotionGates: z.object({
    minToolRecallAt5: z.number().min(0).max(1),
    minExecutionSuccessAtK: z.number().min(0).max(1),
    maxEce: z.number().min(0).max(1),
    maxRegressionRate: z.number().min(0).max(1),
  }).strict(),
}).strict();

export type EncoderTrainingManifestV1 = z.infer<typeof EncoderTrainingManifestV1Schema>;

export const DEFAULT_INTENT_ENCODER_MANIFEST: EncoderTrainingManifestV1 = EncoderTrainingManifestV1Schema.parse({
  schemaVersion: 'atlas.encoder-training-manifest.v1',
  encoderId: 'parent-atlas-intent-domain-v1',
  task: 'intent_domain_classifier',
  baseModel: 'sentence-transformers/all-MiniLM-L6-v2',
  adaptation: 'lora',
  trainSplitRevision: 'UNBOUND',
  validationSplitRevision: 'UNBOUND',
  featureContractRevision: 'atlas.candidate-feature-matrix.v1',
  toolRegistryRevision: 'UNBOUND',
  maxSequenceLength: 256,
  batchSize: 32,
  gradientAccumulationSteps: 1,
  precision: 'fp16',
  targetModules: [],
  rankBudget: 32,
  quantization: 'none',
  metrics: ['tool_recall_at_1', 'tool_recall_at_3', 'tool_recall_at_5', 'ece', 'brier'],
  promotionGates: {
    minToolRecallAt5: 0.98,
    minExecutionSuccessAtK: 0.95,
    maxEce: 0.05,
    maxRegressionRate: 0.02,
  },
});

export const DEFAULT_TOOL_CROSS_ENCODER_MANIFEST: EncoderTrainingManifestV1 = EncoderTrainingManifestV1Schema.parse({
  schemaVersion: 'atlas.encoder-training-manifest.v1',
  encoderId: 'parent-atlas-tool-cross-encoder-v1',
  task: 'tool_cross_encoder',
  baseModel: 'cross-encoder/ms-marco-MiniLM-L-6-v2',
  adaptation: 'lora',
  trainSplitRevision: 'UNBOUND',
  validationSplitRevision: 'UNBOUND',
  featureContractRevision: 'atlas.candidate-feature-matrix.v1',
  toolRegistryRevision: 'UNBOUND',
  maxSequenceLength: 384,
  batchSize: 16,
  gradientAccumulationSteps: 2,
  precision: 'fp16',
  targetModules: [],
  rankBudget: 32,
  quantization: 'none',
  metrics: ['tool_recall_at_1', 'tool_recall_at_3', 'tool_recall_at_5', 'mrr', 'ndcg_at_5', 'execution_success_at_k', 'ece'],
  promotionGates: {
    minToolRecallAt5: 0.99,
    minExecutionSuccessAtK: 0.97,
    maxEce: 0.05,
    maxRegressionRate: 0.02,
  },
});
