import { describe, it, expect } from 'vitest';
import {
  classifySourceKind,
  inferFeatureIdentity,
  inferHmmState,
  deriveSemanticTitleId,
  isSourceKind,
  VALID_SOURCE_KINDS
} from '$lib/server/classifier/source-kind-classifier';

describe('Source Kind Classifier', () => {
  describe('isSourceKind', () => {
    it('should recognize all valid source kinds', () => {
      for (const kind of VALID_SOURCE_KINDS) {
        expect(isSourceKind(kind)).toBe(true);
      }
    });

    it('should reject invalid source kinds', () => {
      expect(isSourceKind('invalid')).toBe(false);
      expect(isSourceKind(123)).toBe(false);
      expect(isSourceKind(null)).toBe(false);
    });
  });

  describe('classifySourceKind', () => {
    it('should classify TypeScript code files', () => {
      expect(classifySourceKind('src/lib/auth.ts')).toBe('code');
      expect(classifySourceKind('src/lib/server/client.ts')).toBe('code');
    });

    it('should classify Svelte components', () => {
      expect(classifySourceKind('src/lib/Button.svelte')).toBe('code');
      expect(classifySourceKind('src/routes/+page.svelte')).toBe('code');
    });

    it('should classify Go files', () => {
      expect(classifySourceKind('go-retrieval-classifier/main.go')).toBe('code');
    });

    it('should classify JavaScript files', () => {
      expect(classifySourceKind('scripts/atlas/extract.mjs')).toBe('code');
    });

    it('should classify specifications', () => {
      expect(classifySourceKind('docs/API_SPEC.md', 'API specification and schema')).toBe('spec');
      expect(classifySourceKind('docs/contract.md', 'Hard requirements: must validate')).toBe('spec');
      expect(classifySourceKind('design.md', 'Architecture design and acceptance criteria')).toBe('spec');
    });

    it('should classify recommendations', () => {
      expect(classifySourceKind('notes.md', 'TODO: add feature X\nNext steps: implement Y')).toBe('recommendation');
      expect(classifySourceKind('roadmap.md', 'Risk: performance degradation\nBlocker: waiting on upstream')).toBe('recommendation');
      expect(classifySourceKind('pr-review.md', 'Recommendation: refactor this logic')).toBe('recommendation');
    });

    it('should classify handoff documents', () => {
      expect(classifySourceKind('session-log.md', 'Session 115 handoff\nCompleted: Phase 3b')).toBe('handoff');
      expect(classifySourceKind('status.md', 'Status: In progress\nMilestone: Phase 6 reached')).toBe('handoff');
      expect(classifySourceKind('summary.txt', 'Work summary for this phase')).toBe('handoff');
    });

    it('should classify user notes', () => {
      expect(classifySourceKind('notes.md', 'User said: this feature is broken\nUser wants: better error handling')).toBe('user_note');
      expect(classifySourceKind('ideas.txt', 'Ideas and observations from testing')).toBe('user_note');
      expect(classifySourceKind('scratchpad.md', 'Quick notes and thoughts')).toBe('scratchpad');
    });

    it('should classify AI-generated content', () => {
      expect(classifySourceKind('generated.md', 'Generated by Claude AI assistant')).toBe('ai_generated');
      expect(classifySourceKind('output.txt', 'Model output from LLM')).toBe('ai_generated');
      expect(classifySourceKind('response.md', 'GPT response to query')).toBe('ai_generated');
    });

    it('should classify test logs', () => {
      expect(classifySourceKind('test-results.log', 'Test execution results\nFailed: 3, Passed: 10')).toBe('test_log');
      expect(classifySourceKind('error.log', 'Stack trace and error details')).toBe('test_log');
      expect(classifySourceKind('validation.txt', 'Validation output passed')).toBe('test_log');
    });

    it('should classify configuration files', () => {
      expect(classifySourceKind('config.ts', 'Configuration file')).toBe('config');
      expect(classifySourceKind('.env', 'Environment variables')).toBe('config');
      expect(classifySourceKind('settings.json', 'Profile and options')).toBe('config');
    });

    it('should default to unknown', () => {
      expect(classifySourceKind('random-file.txt')).toBe('unknown');
      expect(classifySourceKind('data.json')).toBe('unknown');
    });

    it('should be case-insensitive', () => {
      const lower = classifySourceKind('notes.md', 'todo: implement feature');
      const upper = classifySourceKind('notes.md', 'TODO: IMPLEMENT FEATURE');
      expect(lower).toBe(upper);
      expect(lower).toBe('recommendation');
    });
  });

  describe('inferFeatureIdentity', () => {
    it('should infer feature identity from signals', () => {
      const result = inferFeatureIdentity({
        source_ref: 'src/lib/server/auth.ts',
        source_kind: 'code',
        predicted_domain: 'auth',
        keywords: ['session', 'login', 'token']
      });

      expect(result.feature_id).toContain('auth');
      expect(result.feature_id).toContain('session');
      expect(result.feature_label).toContain('auth');
      expect(result.feature_label).toContain('session');
      expect(result.tree_node_id).toContain('code');
      expect(result.tree_node_id).toContain('auth');
      expect(result.tree_node_id).toContain('session');
    });

    it('should handle empty keywords with fallback', () => {
      const result = inferFeatureIdentity({
        source_ref: 'docs/unknown.md',
        source_kind: 'spec',
        predicted_domain: 'general',
        keywords: []
      });

      expect(result.feature_id).toContain('general');
      expect(result.feature_id).toContain('general'); // fallback keyword
      expect(result.tree_node_id).toContain('spec');
    });

    it('should strip sveltekit-frontend prefix', () => {
      const result = inferFeatureIdentity({
        source_ref: 'sveltekit-frontend/src/lib/auth.ts',
        source_kind: 'code',
        predicted_domain: 'auth',
        keywords: ['session']
      });

      expect(result.feature_id).not.toContain('sveltekit-frontend');
    });

    it('should strip scripts/atlas prefix', () => {
      const result = inferFeatureIdentity({
        source_ref: 'scripts/atlas/extract.mjs',
        source_kind: 'code',
        predicted_domain: 'retrieval',
        keywords: ['search']
      });

      expect(result.feature_id).not.toContain('scripts');
      expect(result.feature_id).not.toContain('atlas');
    });

    it('should remove file extensions', () => {
      const result = inferFeatureIdentity({
        source_ref: 'docs/spec.md',
        source_kind: 'spec',
        predicted_domain: 'retrieval',
        keywords: ['query']
      });

      expect(result.feature_id).not.toContain('.md');
    });

    it('should sanitize special characters', () => {
      const result = inferFeatureIdentity({
        source_ref: 'src/lib/[id]/+page.ts',
        source_kind: 'code',
        predicted_domain: 'ui',
        keywords: ['render']
      });

      // Special chars should be replaced
      expect(/[^a-z0-9_.]/.test(result.feature_id)).toBe(false);
    });
  });

  describe('inferHmmState', () => {
    it('should return CANONICAL for high-confidence keywords', () => {
      const state = inferHmmState({
        source_kind: 'code',
        feature_id: 'auth.session.lib_auth',
        tree_node_id: 'code/auth/session',
        domain_confidence: 0.9,
        qdrant_point_id: 'point-123',
        has_keywords: true
      });

      expect(state).toBe('CANONICAL');
    });

    it('should return UNKNOWN for missing feature_id', () => {
      const state = inferHmmState({
        source_kind: 'code',
        feature_id: undefined,
        tree_node_id: 'code/auth/session',
        domain_confidence: 0.9,
        qdrant_point_id: 'point-123',
        has_keywords: true
      });

      expect(state).toBe('UNKNOWN');
    });

    it('should return UNKNOWN for missing tree_node_id', () => {
      const state = inferHmmState({
        source_kind: 'code',
        feature_id: 'auth.session.lib_auth',
        tree_node_id: undefined,
        domain_confidence: 0.9,
        qdrant_point_id: 'point-123',
        has_keywords: true
      });

      expect(state).toBe('UNKNOWN');
    });

    it('should return RECOVERABLE for low confidence', () => {
      const state = inferHmmState({
        source_kind: 'spec',
        feature_id: 'retrieval.search.spec',
        tree_node_id: 'spec/retrieval/search',
        domain_confidence: 0.2,
        qdrant_point_id: 'point-123',
        has_keywords: true
      });

      expect(state).toBe('RECOVERABLE');
    });

    it('should return RECOVERABLE for code without embeddings', () => {
      const state = inferHmmState({
        source_kind: 'code',
        feature_id: 'db.query.client_ts',
        tree_node_id: 'code/database/query',
        domain_confidence: 0.8,
        qdrant_point_id: null,
        has_keywords: true
      });

      expect(state).toBe('RECOVERABLE');
    });

    it('should return RECOVERABLE by default', () => {
      const state = inferHmmState({
        source_kind: 'recommendation',
        feature_id: 'general.todo.roadmap',
        tree_node_id: 'recommendation/general/todo',
        domain_confidence: 0.5,
        qdrant_point_id: 'point-123',
        has_keywords: false
      });

      expect(state).toBe('RECOVERABLE');
    });
  });

  describe('deriveSemanticTitleId', () => {
    it('should derive semantic title ID from identity signals', () => {
      const titleId = deriveSemanticTitleId({
        source_ref: 'src/lib/auth.ts',
        feature_id: 'auth.session.lib_auth',
        derived_title: 'Authentication Session Validator'
      });

      expect(titleId).toContain('hyperrag:rpc:semantic_title_id:');
      expect(titleId.split(':').length).toBe(4);
    });

    it('should be deterministic', () => {
      const packet = {
        source_ref: 'docs/spec.md',
        feature_id: 'retrieval.query.spec',
        derived_title: 'Retrieval Query Specification'
      };

      const id1 = deriveSemanticTitleId(packet);
      const id2 = deriveSemanticTitleId(packet);

      expect(id1).toBe(id2);
    });

    it('should handle missing optional fields', () => {
      const titleId = deriveSemanticTitleId({
        source_ref: 'unknown.txt'
      });

      expect(titleId).toContain('hyperrag:rpc:semantic_title_id:');
    });

    it('should sanitize special characters', () => {
      const titleId = deriveSemanticTitleId({
        source_ref: 'src/[id]/+page.ts',
        feature_id: 'ui.render.page',
        derived_title: 'Page Render: [ID] Dynamic'
      });

      // Should only contain alphanumeric, underscore, colon
      const parts = titleId.split(':').slice(3).join('');
      expect(/[^a-z0-9_]/.test(parts)).toBe(false);
    });

    it('should combine all identity signals', () => {
      const titleId1 = deriveSemanticTitleId({
        source_ref: 'src/lib/auth.ts',
        feature_id: 'auth.session.lib_auth',
        derived_title: 'Auth Session'
      });

      const titleId2 = deriveSemanticTitleId({
        source_ref: 'src/lib/auth.ts',
        feature_id: 'auth.login.lib_auth',
        derived_title: 'Auth Login'
      });

      // Different feature_id and title should produce different IDs
      expect(titleId1).not.toBe(titleId2);
    });
  });

  describe('Integration', () => {
    it('should flow through complete classification pipeline', () => {
      // Code lane
      const codeSourceRef = 'src/lib/retrieval/query.ts';
      const codeKind = classifySourceKind(codeSourceRef, 'export function search() { ... }');
      expect(codeKind).toBe('code');

      const codeIdentity = inferFeatureIdentity({
        source_ref: codeSourceRef,
        source_kind: codeKind,
        predicted_domain: 'retrieval',
        keywords: ['search', 'query']
      });

      const codeHmm = inferHmmState({
        source_kind: codeKind,
        feature_id: codeIdentity.feature_id,
        tree_node_id: codeIdentity.tree_node_id,
        domain_confidence: 0.95,
        qdrant_point_id: 'point-abc',
        has_keywords: true
      });

      expect(codeHmm).toBe('CANONICAL');

      // Docs lane
      const docSourceRef = 'docs/retrieval-contract.md';
      const docKind = classifySourceKind(docSourceRef, 'Specification: retrieval contract defines search semantics');
      expect(docKind).toBe('spec');

      const docIdentity = inferFeatureIdentity({
        source_ref: docSourceRef,
        source_kind: docKind,
        predicted_domain: 'retrieval',
        keywords: ['spec', 'contract']
      });

      const docHmm = inferHmmState({
        source_kind: docKind,
        feature_id: docIdentity.feature_id,
        tree_node_id: docIdentity.tree_node_id,
        domain_confidence: 0.88,
        qdrant_point_id: null,
        has_keywords: true
      });

      expect(docHmm).toBe('RECOVERABLE');

      // Both should flow to HMM + RRF
      expect(codeIdentity.feature_label).toContain('retrieval');
      expect(docIdentity.feature_label).toContain('retrieval');
    });
  });
});
