export function buildParentAtlasAgentContractLines(): string[] {
  return [
    '## Parent Atlas Agent Contract',
    '',
    'Purpose: Parent Atlas builds indexed CHROM97/NESCHROM97 packets for HyperRAG dense search and OpenCode agentic retrieval.',
    'The model must retrieve Parent Atlas packets first, then read source files only when needed.',
    '',
    'Core terms:',
    '- Parent Atlas: canonical index spine for packet identity, source_ref, feature_id, topology, and retrieval metadata.',
    '- CHROM97/NESCHROM97 packet: JSON packet containing source evidence, runtime evidence, topology labels, ontology labels, embeddings, graph links, scores, and recommendations.',
    '- ACE hit: a retrieved packet that is actionable by an agent.',
    '- ACP: Agent Command Packet, a task envelope containing objective, allowed tools, packet filters, source_ref requirements, and verification rules.',
    '- HyperRAG: fusion layer combining dense search, graph topology, tags, runtime traces, Redis/Bifrost mirrors, and source_ref evidence.',
    '',
    '## Open Lanes',
    '',
    '1. Neo4j / GDS topology pass — compute graph neighbors, communities, PageRank, centrality, and topology labels.',
    '2. Packet reader / writer — read/write CHROM97/NESCHROM97 LDJSON deterministically.',
    '3. HyperRAG fusion wiring — combine Qdrant dense hits, BM25/RRF, Neo4j graph signals, Redis/Bifrost mirrors, and ACE scoring.',
    '4. Qdrant tag mirroring — mirror source_ref, feature_id, community_id, ontology_label, topology_label, and packet_key into vector payloads.',
    '5. SOM 20x20 / auto-clustering — assign packets into topology cells and cluster labels.',
    '6. Artifact tiering — classify raw, derived, embedding, checkpoint, and cache artifacts.',
    '7. Phase 17 runtime recovery — keep Valkey/Bifrost/Go Retrieval available as runtime mirrors/search workers.',
    '',
    '## Agent Rules',
    '',
    'Always retrieve packets before broad source search.',
    '',
    'Always prefer: packet_key, source_ref, canonical_source_ref, feature_id, community_id, cluster_key, ontology_label, topology_label.',
    '',
    'Never use generated files as canonical truth.',
    'Generated files may be used only as runtime evidence if source = dynamic_tracer, run_id exists, and evidence maps back to canonical_source_ref.',
    '',
    'Exclude from static source capture: node_modules/, .svelte-kit/, .vite/, dist/, build/, .env*, *.pem, *.key',
    '',
    'ACE hit shape: packet_key, packet_type, source_ref, canonical_source_ref, feature_id, score, reason, recommended_action, verification_command.',
    '',
    'Tool calling rule: emit valid tool calls only, do not wrap tool calls in markdown, do not invent source refs, do not invent files, do not patch before retrieval.',
    '',
    '## Build Order',
    '',
    '1. packet reader / writer',
    '2. runtime evidence collector',
    '3. Qdrant tag mirroring',
    '4. Neo4j / GDS topology pass',
    '5. HyperRAG fusion',
    '6. Go Retrieval binding',
    '7. SOM 20x20',
    '8. artifact tiering',
    '',
  ];
}
